.gitignore
README.md

* Add prerequisites to README.md
* Update .gitignore for JetBrains Rider

Add prerequisites to README.md

---

Digdir.Domain.Dialogporten.sln.DotSettings
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogActivities/Queries/Get/GetDialogActivityQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogActivities/Queries/List/ListDialogActivityQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogElements/Queries/Get/GetDialogElementDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogElements/Queries/Get/GetDialogElementQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogElements/Queries/Get/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogElements/Queries/List/ListDialogElementDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogElements/Queries/List/ListDialogElementQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogElements/Queries/List/MappingProfile.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogElement/GetDialogElementEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogElement/ListDialogElementEndpoint.cs

Listerespons:
```
[
{
"id": "901d8a01-9b69-2175-84c4-8aa0b1e4dd14",
"createdAt": "2023-08-22T14:05:18.1048440Z",
"updatedAt": "2023-08-22T14:05:18.1048440Z",
"type": "some:type",
"dialogId": "901d8a01-7369-9c76-9e9e-78c20af31212",
"displayName": [
{
"value": "Et annet vedlegg",
"cultureCode": "nb-no"
}
],
"relatedDialogElementId": "d44db68b-f470-4a00-bb5a-d11f0a2d6dd3"
},
{
"id": "d44db68b-f470-4a00-bb5a-d11f0a2d6dd3",
"createdAt": "2023-08-22T14:05:18.1048440Z",
"updatedAt": "2023-08-22T14:05:18.1048440Z",
"type": "some:type",
"dialogId": "901d8a01-7369-9c76-9e9e-78c20af31212",
"displayName": [
{
"value": "Et vedlegg",
"cultureCode": "nb-no"
}
]
}
]
```
Singelrespons:
```
{
"id": "d44db68b-f470-4a00-bb5a-d11f0a2d6dd3",
"createdAt": "2023-08-22T14:05:18.1048440Z",
"updatedAt": …
```

Add EndUser dialog elements endpoints

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommand.cs

Check correct activity id list when creating new dialog

---

src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/ServiceOwnerGroup.cs

Makes it match path endpoint and enduser endpoints

Make serviceowner path lowercase

---

src/Digdir.Domain.Dialogporten.WebApi/appsettings.Development.json
src/Digdir.Domain.Dialogporten.WebApi/appsettings.json

Fixes #52 
Merge/deploy after https://github.com/Altinn/altinn-events/pull/375 is in TT02.

Use admin scope for events production

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/List/ListDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/List/ListDialogQueryValidator.cs

Remove rule for ServiceResource/Party

---

Digdir.Domain.Dialogporten.sln
src/Digdir.Domain.Dialogporten.Application/Common/Expressions.cs
src/Digdir.Domain.Dialogporten.Application/Common/Extensions/Enumerables/General.cs
src/Digdir.Domain.Dialogporten.Application/Common/Extensions/Enumerables/MergeExtensions.cs
src/Digdir.Domain.Dialogporten.Application/Common/Extensions/Enumerables/UpdateSet.cs
src/Digdir.Domain.Dialogporten.Application/Common/Extensions/QueryableExtensions.cs
src/Digdir.Domain.Dialogporten.Application/Externals/AltinnAuthorization/DialogSearchAuthorizationResult.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Localizations/LocalizationService.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogQueryValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/SearchDialogQuery.cs
src/Digdir.Tool.Dialogporten.Benchmarks/Digdir.Tool.Dialogporten.Benchmarks.csproj
src/Digdir.Tool.Dialogporten.Benchmarks/Program.cs
src/Digdir.Tool.Dialogporten.Benchmarks/QueryableExtensionsBenchmark.cs

- Rewrite "WhereUserIsAuthorizedFor" to use low level Expression statements.
- Add benchmark project.

Fix issue where "WhereUserIsAuthorizedFor" was a one hit wonder.

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogActivities/Queries/Get/GetDialogActivityQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogActivities/Queries/Search/SearchDialogActivityQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogElements/Queries/Get/GetDialogElementQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogElements/Queries/Search/SearchDialogElementQuery.cs

Add resource registry check on elements/activities

---

.azure/containerApp/createExternal.bicep

Dette ble disabled da vi debugget hva det var som gjorde at container-appsa tryna i Azure

Re-enable ip restrictions on container app ingress

---

.editorconfig
.github/workflows/BuildTestPublish.yml
.github/workflows/e2e-tests.yml
.github/workflows/perftest-createdelete.yml
README.md
docker-compose-no-webapi.yml
src/Digdir.Domain.Dialogporten.Application/Digdir.Domain.Dialogporten.Application.csproj
src/Digdir.Domain.Dialogporten.ChangeDataCapture/Digdir.Domain.Dialogporten.ChangeDataCapture.csproj
src/Digdir.Domain.Dialogporten.ChangeDataCapture/Dockerfile
src/Digdir.Domain.Dialogporten.Domain/Digdir.Domain.Dialogporten.Domain.csproj
src/Digdir.Domain.Dialogporten.Infrastructure/Digdir.Domain.Dialogporten.Infrastructure.csproj
src/Digdir.Domain.Dialogporten.Infrastructure/MigrationBundle.dockerfile
src/Digdir.Domain.Dialogporten.Service/Digdir.Domain.Dialogporten.Service.csproj
src/Digdir.Domain.Dialogporten.Service/Dockerfile
src/Digdir.Domain.Dialogporten.Service/appsettings.Development.json
src/Digdir.Domain.Dialogporten.WebApi/Common/Extensions/AspNetCoreOpenApiDocumentGeneratorSettingsExtensions.cs
src/Digdir.Domain.Dialogporten.WebApi/Digdir.Domain.Dialogporten.WebApi.csproj
src/Digdir.Domain.Dialogporten.WebApi/Dockerfile
src/Digdir.Library.Entity.Abstractions/Digdir.Library.Entity.Abstractions.csproj
src/Digdir.Library.Entity.EntityFrameworkCore/Digdir.Library.Entity.EntityFrameworkCore.csproj
src/Digdir.Tool.Dialogporten.Benchmarks/Digdir.Tool.Dialogporten.Benchmarks.csproj
src/Digdir.Tool.Dialogporten.MigrationVerifier/Digdir.Tool.Dialogporten.MigrationVerifier.csproj
src/Digdir.Tool.Dialogporten.MigrationVerifier/Dockerfile
src/Digdir.Tool.Dialogporten.SlackNotifier/Digdir.Tool.Dialogporten.SlackNotifier.csproj
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Digdir.Domain.Dialogporten.Application.Integration.Tests.csproj
tests/Digdir.Domain.Dialogporten.Infrastructure.Unit.Tests/Digdir.Domain.Dialogporten.Infrastructure.Unit.Tests.csproj

Upgrade to .NET8

---

src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/DialogDbContext.cs

Ignore query filters when checking for existing IDs

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/SearchDialogDto.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/DialogEntity.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20231215174628_AddProgressToDialog.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20231215174628_AddProgressToDialog.cs

Add Progress field to DialogEntity

---

src/Digdir.Domain.Dialogporten.Application/Common/Extensions/QueryableExtensions.cs
src/Digdir.Domain.Dialogporten.Application/Externals/IDialogDbContext.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Delete/DeleteDialogCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Content/DialogContentType.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/DialogEntity.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Configurations/Dialogs/Content/DialogContentConfiguration.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/DialogDbContext.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20231218124413_RenameETagToRevision.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20231218124413_RenameETagToRevision.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Authentication/JwtSchemeSelectorMiddleware.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Authentication/TokenIssuerCache.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Constants.cs
src/Digdir.Domain.Dialogporten.WebApi/Digdir.Domain.Dialogporten.WebApi.csproj
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/Dialogs/GetDialogEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogActivities/CreateDialogActivityEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogElements/CreateDialogElementEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogElements/DeleteDialogElementEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogElements/UpdateDialogElementEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/DeleteDialogEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/GetDialogEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/PatchDialogsController.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/UpdateDialogEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Program.cs
src/Digdir.Library.Entity.Abstractions/Features/Versionable/IVersionableEntity.cs
src/Digdir.Library.Entity.Abstractions/Features/Versionable/VersionableExtensions.cs
src/Digdir.Library.Entity.EntityFrameworkCore/Features/Versionable/VersionableExtensions.cs
src/Digdir.Tool.Dialogporten.Benchmarks/QueryableExtensionsBenchmark.cs

Renames ETag to Revision, add ETag header to EU endpoint

---

.vscode/launch.json
.vscode/tasks.json

For oss som bruker Visual Studio Code 🙋

chore: add vscode settings for run and debug web api

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogQuery.cs

#250 
Manglet descsription og performedBy

Include description and performedBy on EU detailed dialog dto

---

src/Digdir.Domain.Dialogporten.Infrastructure/Common/Extensions/DistributedCacheExtensions.cs

Issue #340 ref https://github.com/digdir/dialogporten/pull/340#discussion_r1449999941

Implement locking mechanism to prevent cache stampede

---

.github/workflows/Deploy.yml

This is gonna bite us in the a**. Let's not do this.

ci: avoid cancelling deploy in progress

---

.github/workflows/Publish.yml

Derived from https://github.com/digdir/dialogporten/pull/374

ci: ensure dotnet is cached

---

src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/DialogStatus.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240126124043_RenameUnspecifiedToNew.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240126124043_RenameUnspecifiedToNew.cs

(chore) Rename dialog status Unspecified to New

---

index.md

https://github.com/digdir/dialogporten/pull/368

docs: Update read to seen

---

.github/tools/README.md
src/Digdir.Domain.Dialogporten.Infrastructure/MigrationBundle.dockerfile

fix: try echoing pgpassword in migration job🤫

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogDto.cs

#370 
Latest activities og progress er tatt i andre PRs

feat: Add element count to eu list dto

---

.azure/applications/web-api-so/main.bicep
src/Digdir.Domain.Dialogporten.WebApi/appsettings.test.json

* Remove adding apim to app configuration
* Add the base uri for the container app in appsettings

chore: remove adding apim in app configuration

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Localizations/LocalizationDtoValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommandValidator.cs

fix: Check Content for null, use DependentRules, disallow empty localization values

---

.github/workflows/action-check-for-changes.yml

Add checks to avoid unintentional skipping of deployments

ci: add better checks for files changed

---

src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureExtensions.cs

https://altinndevops.slack.com/archives/C05V9GB6QAJ/p1707830854582679

Set split query behavior as default

---

src/Digdir.Domain.Dialogporten.Application/Common/Extensions/AutoMapperExtensions.cs
src/Digdir.Domain.Dialogporten.Application/Common/Extensions/FluentValidation/FluentValidation_LocalizationDto_Extensions.cs
src/Digdir.Domain.Dialogporten.Application/Common/Extensions/OneOfExtensions.cs
src/Digdir.Domain.Dialogporten.Application/Common/ReturnTypes/EntityDeleted.cs
src/Digdir.Domain.Dialogporten.Application/Common/ReturnTypes/EntityNotFound.cs
src/Digdir.Domain.Dialogporten.Application/Common/ReturnTypes/Forbidden.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/Outboxes/Commands/Delete/DeleteOutboxMessagesCommand.cs
src/Digdir.Domain.Dialogporten.ChangeDataCapture/ChangeDataCapture/ICdcSubscription.cs
src/Digdir.Domain.Dialogporten.Domain/Parties/Abstractions/PartyIdentifier.cs
src/Digdir.Domain.Dialogporten.Domain/Parties/NorwegianOrganizationIdentifier.cs
src/Digdir.Domain.Dialogporten.Domain/Parties/NorwegianPersonIdentifier.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/DecisionRequestHelper.cs
src/Digdir.Domain.Dialogporten.Infrastructure/DomainEvents/Outbox/Dispatcher/IdempotentDomainEventHandler.cs
src/Digdir.Library.Entity.EntityFrameworkCore/Features/SoftDeletable/SoftDeletableExtensions.cs
src/Digdir.Tool.Dialogporten.SlackNotifier/External/AppInsights/IAppInsightsClient.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Dialogs/Commands/CreateDialogTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Dialogs/Queries/GetDialogTests.cs
tests/Digdir.Domain.Dialogporten.Infrastructure.Unit.Tests/DecisionRequestHelperTests.cs
tests/Digdir.Domain.Dialogporten.Infrastructure.Unit.Tests/QueryableExtensionsTests.cs

chore: Use collection expression

---

.github/workflows/action-build-and-test.yml
.github/workflows/action-deploy-function.yml
Directory.Build.props
global.json

* Adds global.json, locking dotnet version to `8.0.201`, without rollForward
* Sets AnalysisLevel to 8
* Locks dotnet version in GitHub Actions

chore: Add global.json

---

src/Digdir.Domain.Dialogporten.WebApi/Dockerfile

This is just a test for a demo of the new workflow

fix: add extra comment in dockerfile

---

.azure/applications/web-api-eu/main.bicep
.azure/applications/web-api-so/main.bicep

We used a custom access policy which is not required as Data Contributor meets our needs.

fix(azure): use built-in policy for redis

---

.azure/infrastructure/main.bicep
.azure/modules/redis/main.bicep

Added the hostname directly in app configuration instead of using the secret URI

fix(azure): use secret uri instead of host name in app config

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogDto.cs

chore: Remove ReadAt

---

README.md

docs: install podman on windows

---

tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Common/Events/DomainEventsTests.cs

Disabling event assertion to make the pipeline chug along

chore: Temp disable test

---

.github/workflows/action-check-for-changes.yml
src/Digdir.Tool.Dialogporten.SlackNotifier/Features/AzureAlertToSlackForwarder/ForwardAlertToSlack.cs

Check for changes was using the old paths-filter name

ci: Use correct step name

---

src/Digdir.Domain.Dialogporten.Application/Common/Extensions/FluentValidation/FluentValidation_PartyIdentifier_Extensions.cs

fix: Add PartyIdentifier.Separator to party validation error

---

src/Digdir.Domain.Dialogporten.Application/ApplicationExtensions.cs
src/Digdir.Domain.Dialogporten.Application/Common/ICompactJwsGenerator.cs
src/Digdir.Domain.Dialogporten.Application/Common/MappingUtils.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogActivities/Queries/Get/GetDialogActivityQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogActivities/Queries/Search/SearchDialogActivityQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogQuery.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/DialogEntity.cs
src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureExtensions.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogActivities/Get/GetDialogActivityEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogActivities/Search/SearchDialogActivityEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogElements/Get/GetDialogElementEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogElements/Search/SearchDialogElementEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogElements/Update/UpdateDialogElementEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Purge/PurgeDialogEndpoint.cs

* Removed salt input, weird behavior to take input that the tool itself has generated
* Changed old name, it used to be related to mapping
* Put it in the DI container

chore: Refactor MappingUtils

---

docs/swagger/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/SearchDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/SearchDialogQuery.cs

Not marking as feat., there is already a PR merged that adds the SeenLog split in the changelog.
Will edit changelog with more notes before merging 1.4.0

chore: Add seen log to service owner

---

docs/swagger/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Get/GetDialogSeenLogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Get/GetDialogSeenLogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Get/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Search/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Search/SearchDialogSeenLogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Search/SearchDialogSeenLogQuery.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogSeenLogs/Get/GetDialogSeenLogEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogSeenLogs/Get/GetDialogSeenLogSwaggerConfig.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogSeenLogs/Search/SearchDialogSeenLogEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogSeenLogs/Search/SearchDialogSeenLogSwaggerConfig.cs

* New SeenLog endpoints for ServiceOwner
* Updated swagger
Marking as chore, don't need another entry in the changelog.  
I will make a manual edit on this before merging 1.4.0.
Adding tests in separate PR.
#460

chore: Add seen log SO endpoints

---

.github/tools/containerAppJobVerifier.sh

Using version instead of git sha to be more specific about the query.

chore: use version and image tag in container app job verifier

---

docs/CommonAPIM.md

Adding minor details to the APIM guide

chore: Minor command fix in apim readme

---

src/Digdir.Domain.Dialogporten.Application/Common/IUserOrganizationRegistry.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Get/GetDialogSeenLogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Search/SearchDialogSeenLogQuery.cs

chore: Remove unused fields

---

src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogSeenLogs/Search/SearchDialogSeenLogEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogElements/Get/GetDialogElementEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogElements/Get/GetDialogElementSwaggerConfig.cs
src/Digdir.Library.Entity.Abstractions/Features/Aggregate/AggregateNode.cs
src/Digdir.Library.Entity.Abstractions/Features/Aggregate/IAggregateChangedHandler.cs
src/Digdir.Library.Entity.Abstractions/Features/EventPublisher/IDomainEvent.cs
src/Digdir.Library.Entity.EntityFrameworkCore/Features/Aggregate/AggregateExtensions.cs

chore: Minor typos

---

docker-compose-no-webapi.yml
docker-compose.yml

Ensures that migrations are run when running docker-compose

chore: add migration in docker compose

---

.azure/modules/postgreSql/create.bicep
docker-compose-no-webapi.yml

New major version of flexible PostgreSQL available in our Azure region

chore: Update to postgres 16

---

docs/swagger/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogDto.cs

Forgot to change these on @arealmaas suggestion on the SeenLog endpoint PR

chore: Consolidate SeenLog naming, change CreatedAt to SeenAt

---

docker-compose.yml

chore: revert port change for web api in compose

---

docs/schema/V1/package.json

Was published under my username 🙅‍♂️

chore: Add missing organization name for schema npm package [skip ci]

---

src/Digdir.Domain.Dialogporten.GraphQL/Common/ApplicationUser.cs
src/Digdir.Domain.Dialogporten.GraphQL/Common/Authentication/AuthenticationBuilderExtensions.cs
src/Digdir.Domain.Dialogporten.GraphQL/Program.cs

Hard coded IUser set to LocalDevelopmentUser
- #490

chore(GraphQl): Add application user

---

src/Digdir.Domain.Dialogporten.Application/Common/ITransactionTime.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogSeenLogs/Queries/Get/GetDialogSeenLogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Get/GetDialogSeenLogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Search/SearchDialogSeenLogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/WellKnown/Jwks/Queries/Get/GetJwksDto.cs
src/Digdir.Domain.Dialogporten.GraphQL/ApplicationInsightEventListener.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/ResourceRegistry/ResourceRegistryClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureExtensions.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/ApplicationUser.cs
src/Digdir.Tool.Dialogporten.GenerateFakeData/DialogGenerator.cs
tests/Digdir.Domain.Dialogporten.Infrastructure.Unit.Tests/DecisionRequestHelperTests.cs

Minor code/comment cleaning 🧹 
* Unused usings
* Expression bodies
* Trailing commas
* Collection expressions
* Remove unnecessary fields
* Redundant namespace
* Use const
* Grammar

chore: Code cleaning

---

.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-staging.yml

Ensure that we run all the jobs regardless if any files has changed when we do a manual dispatch of the workflows

ci: run all jobs on dispatch for main and staging

---

docker-compose-no-webapi.yml

Adds [RedisInsight](https://redis.io/insight/) to the compose setup

chore(docker-compose): Add RedisInsight

---

tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Common/Events/DomainEventsTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/DialogCqrsCollectionFixture.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/EndUser/Dialogs/Queries/SeenLogTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/CreateDialogTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/DeleteDialogTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/PurgeDialogTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/UpdateDialogTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Queries/GetDialogTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Queries/SearchDialogTests.cs

Splits tests into folders for EndUser/ServiceOwner

chore(tests): Restructure application integration tests

---

docs/schema/V1/package.json
docs/schema/V1/schema.verified.graphql
src/Digdir.Domain.Dialogporten.Application/Common/ReturnTypes/EntityNotFound.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/Common/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/DialogById/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/DialogQueries.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/SearchDialogs/MappingProfile.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/SearchDialogs/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.GraphQL/ServiceCollectionExtensions.cs

Adds typed errors to the GraphQl schema
- #490

chore: Graphql error handling

---

.github/ISSUE_TEMPLATE/new-change-in-functionality.md

Added checkbox to confirm if security impact has been evaluated when creating issue for new or changed functionality

chore: confirm evaluation of security impact for new issues

---

.github/workflows/action-deploy-apps.yml
.github/workflows/action-deploy-infra.yml

chore: upgrade az cli version

---

global.json
src/Digdir.Domain.Dialogporten.ChangeDataCapture/Dockerfile
src/Digdir.Domain.Dialogporten.GraphQL/Dockerfile
src/Digdir.Domain.Dialogporten.Infrastructure/MigrationBundle.dockerfile
src/Digdir.Domain.Dialogporten.Service/Dockerfile
src/Digdir.Domain.Dialogporten.WebApi/Dockerfile

New security patch out
https://dotnet.microsoft.com/en-us/download/dotnet/8.0

chore: Update .NET SDK

---

.github/workflows/dispatch-apps.yml

Adding a dispatch to be able to deploy apps given a version and environment input value

ci: enable dispatch of apps

---

src/Digdir.Domain.Dialogporten.WebApi/Program.cs

fix(webapi): Fix Swagger URL for new APIM

---

src/Digdir.Domain.Dialogporten.WebApi/Program.cs

This reverts commit 2388d5491f7ae1f9166e3ca84b07cf47e887dadd.

chore: Revert "Fix Swagger URL for new APIM"

---

.azure/infrastructure/main.bicep
.azure/modules/serviceBus/main.bicep

- Disable public access for servicebus
- Use correct vnetID for private DNS zone
- #686

chore(azure): disable public access for servicebus

---

.editorconfig

chore: Don't prefer specifying types when using new() { ... }

---

.github/workflows/action-deploy-infra.yml

chore(azure): enable debug when deploying infra

---

.github/workflows/action-deploy-infra.yml

chore(azure): fix deployment of infra

---

.github/workflows/action-deploy-infra.yml

chore(azure): remove debug from infra deployment

---

.github/workflows/action-deploy-infra.yml

chore(azure): separate dryrun from deploy

---

.github/workflows/action-deploy-apps.yml

chore(azure): separate dryrun from deploy when deploying apps

---

src/Digdir.Domain.Dialogporten.Service/Program.cs

chore: Trigger new revision

---

.github/workflows/action-deploy-apps.yml

fix(ci): separate migration-job deployments

---

docs/schema/V1/package-lock.json

fix(schema): add package-lock file

---

.github/workflows/action-publish-schema.yml
docs/schema/V1/README.md

ci(schema): use correct working-directory

---

.github/workflows/ci-cd-main.yml
docs/schema/V1/package.json

ci(schema): use correct version for schema publishing

---

.azure/modules/functionApp/slackNotifier.bicep

Got notified about the issue in GH security scanning: https://github.com/digdir/dialogporten/security/code-scanning/5

chore: fix security vulnerability for slacknotifier

---

docs/schema/V1/schema.verified.graphql
docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Actions/DialogGuiAction.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/DialogById/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240607182219_RemoveIsBackChannelFromGuiAction.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240607182219_RemoveIsBackChannelFromGuiAction.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Update/UpdateDialogSwaggerConfig.cs

This removes the `IsBackChannel` flag from GUI Actions.
(Dialogporten as token issuer is the new solution for this)

feat: Remove IsBackChannel concept from GUI Actions

---

.azure/infrastructure/main.bicep
.azure/modules/privateDnsZoneGroup/main.bicep
.azure/modules/redis/main.bicep
.azure/modules/vnet/main.bicep

chore(azure): add private link to redis

---

.azure/modules/redis/main.bicep

chore(azure): fix group id for redis

---

docs/schema/V1/schema.verified.graphql
docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Actions/DialogGuiAction.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/DialogById/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240608131804_RenameIsDeleteActionToIsDeleteDialogAction.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240608131804_RenameIsDeleteActionToIsDeleteDialogAction.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Update/UpdateDialogSwaggerConfig.cs

Better distinction between an action that is method DELETE and an action that deletes the dialog

feat: Rename IsDeleteAction to IsDeleteDialogAction

---

.github/workflows/action-check-for-changes.yml

Seems like any_changed doesn't take into account deleted files. Changing to any_modified https://github.com/tj-actions/changed-files/tree/v44/?tab=readme-ov-file#output_any_modified

ci: fix check for changes to work with deleted files

---

src/Digdir.Library.Entity.EntityFrameworkCore/Features/Aggregate/AggregateExtensions.cs

Because of the new model changes, we no longer need to load all children when changing the dialog aggregate.
We leave the code in case we need it in the future. (If sub entities require their own deleted/updated events)
- #557 
- #836

chore: Disable loading of aggregate children

---

.azure/modules/keyvault/create.bicep

chore(azure): enable purge protection for env key vault

---

src/Digdir.Domain.Dialogporten.ChangeDataCapture/ChangeDataCapture/Checkpoints/CheckpointSyncronizer.cs
src/Digdir.Domain.Dialogporten.ChangeDataCapture/ChangeDataCapture/Checkpoints/ICheckpointRepository.cs
src/Digdir.Domain.Dialogporten.ChangeDataCapture/ChangeDataCapture/Mappers/DynamicReplicationDataMapper.cs
src/Digdir.Domain.Dialogporten.ChangeDataCapture/ChangeDataCapture/Mappers/IReplicationMapper.cs
src/Digdir.Domain.Dialogporten.ChangeDataCapture/ChangeDataCapture/Subscriptions/ICdcSubscription.cs
src/Digdir.Domain.Dialogporten.ChangeDataCapture/Common/Extensions/NpgsqlDataSourceExtensions.cs
src/Digdir.Domain.Dialogporten.ChangeDataCapture/ICdcSink.cs
src/Digdir.Domain.Dialogporten.ChangeDataCapture/Outbox/IOutboxReaderRepository.cs
src/Digdir.Domain.Dialogporten.ChangeDataCapture/Outbox/OutboxCdcSubscription.cs
src/Digdir.Domain.Dialogporten.ChangeDataCapture/Outbox/OutboxReplicationMapper.cs
src/Digdir.Domain.Dialogporten.ChangeDataCapture/Program.cs

* Removed unused usings
* Remove conditional access
* Use collection expression
* Make methods private
* Remove unused local variable

chore: CDC improvements cleanup suggestion

---

.github/workflows/ci-cd-pull-request.yml

Run a dry-run to verify the Bicep-deployment of the apps

ci: add dry run deployment of apps

---

.azure/modules/keyvault/create.bicep

chore(azure): enable rbac for env key vault

---

docs/schema/V1/schema.verified.graphql
docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/DialogStatus.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/Common/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240723074643_RestructureDialogStatus.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240723074643_RestructureDialogStatus.cs

feat: Rename DialogStatus enum values

---

.github/workflows/action-publish-schema.yml
docs/schema/V1/.gitignore
docs/schema/V1/.npmignore
docs/schema/V1/gql-to-js.js
docs/schema/V1/package-lock.json
docs/schema/V1/package.json
docs/schema/V1/tests/__snapshots__/pack.spec.ts.snap
docs/schema/V1/tests/pack.spec.ts
docs/schema/V1/tests/validate-schema.spec.ts

- Wraps the GraphQL schema into a JavaScript file that exports it as a variable.
- Adds some unit tests to the publishing process.

ci: add build script to `npm publish`

---

docs/schema/V1/schema.verified.graphql
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Activities/DialogActivityType.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/Common/ObjectTypes.cs
src/Digdir.Tool.Dialogporten.GenerateFakeData/DialogGenerator.cs

* Translated old/new summaries from Norwegian to English
* Added/copied missing validation to UpdateValidator
* Updated ActivityType in GraphQL object type/schema
* Fixed broken test

chore: Dialog activity fix/addons

---

tests/k6/common/dialog.js
tests/k6/common/token.js
tests/k6/tests/enduser/dialogDetails.js
tests/k6/tests/enduser/dialogSearch.js
tests/k6/tests/serviceowner/concurrency.js
tests/k6/tests/serviceowner/testdata/01-create-dialog.js

This updates the e2e tests to support new actor model. This also disables the org-filter check as there is currently no appropiate way to implement it.
- #851

fix: Update e2e tests for actor model

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Content/DialogContentInputConverter.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Content/PropertyInfoWithNullability.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommandValidator.cs

Minor cleanups missing from #905

chore: Missing cleanup for content restructure PR (#905)

---

docs/schema/V1/package-lock.json
docs/schema/V1/package.json

Replaces https://github.com/digdir/dialogporten/pull/924 and https://github.com/digdir/dialogporten/pull/925

chore(schema): lock and upgrade dependencies

---

docker-compose-db-redis.yml
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Common/DialogApplication.cs

Matching the current version in Azure

chore: Update Docker Compose/TestContainers PostgreSQL version to 15.7

---

.github/workflows/action-publish-schema.yml

ci: add correct permissions for npm publishing

---

.github/workflows/action-deploy-function.yml
.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-staging.yml

The function apps have changed names based on the unique hash added as postfix. Resolving for now by using the new name instead. For later it should be resolved more automatically, perhaps by using tags or updating secrets in gh actions from IAC

ci: fix deployment of function app

---

src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Transmissions/DialogTransmission.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Configurations/Dialogs/Activities/DialogActivityConfiguration.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Configurations/Dialogs/Transmissions/DialogTransmissionConfiguration.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240731092526_AddRelatedActivitiesConfigForTransmissions.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240731092526_AddRelatedActivitiesConfigForTransmissions.cs

Missed this during the introduction of Transmissions

chore: Fix onDelete behaviour for RelatedTransmissions

---

.github/workflows/dispatch-apps.yml
.github/workflows/dispatch-infrastructure.yml

Using the same input type as dispatching of apps. Later we need to separate between version and ref to ensure we can hot-deploy to staging without needing a git-tag

ci: ensure dispatch of infrastructure works similar as dispatch of apps

---

docs/schema/V1/schema.verified.graphql
docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogActivities/Queries/Get/GetDialogActivityDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogActivities/Queries/Search/SearchDialogActivityDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogDtoBase.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogActivities/Queries/Get/GetDialogActivityDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogActivities/Queries/Search/SearchDialogActivityDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/SearchDialogDtoBase.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Activities/DialogActivity.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Transmissions/DialogTransmission.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/Common/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Configurations/Dialogs/Activities/DialogActivityConfiguration.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240731104826_AddTransmissionRelationOnActivity.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240731104826_AddTransmissionRelationOnActivity.cs

Missed relation in  #858 PR ( #919 )

chore: Add TransmissionId relation to Activity

---

.azure/infrastructure/main.bicep

In order to separate resources in Azure for Arbeidsflate and Dialogporten

fix(azure): add product tag on all resources

---

.azure/applications/graphql/main.bicep
.azure/applications/web-api-eu/main.bicep
.azure/applications/web-api-migration-job/main.bicep
.azure/applications/web-api-so/main.bicep
.azure/modules/containerApp/main.bicep
.azure/modules/containerAppJob/main.bicep

feat(azure): add tags on azure applications

---

.github/workflows/action-deploy-infra.yml

chore: ensure ssh secret key is set when deploying infra

---

.github/workflows/ci-cd-main.yml

ci: use new release please package

---

.github/workflows/action-check-for-changes.yml
.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-pull-request.yml

Ensure that we run a build and test whenever the test files are changed

ci: run tests when test files changed

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogDtoBase.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Search/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Search/SearchDialogSeenLogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSeenLogs/Queries/Search/SearchSeenLogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/SearchDialogDtoBase.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogActivities/NotificationCondition/NotificationConditionSwaggerConfig.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogSeenLogs/Search/SearchDialogSeenLogEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogSeenLogs/Search/SearchDialogSeenLogSwaggerConfig.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/WellKnown/OauthAuthorizationServer/Get/GetOauthAuthorizationServerSwaggerConfig.cs
tests/Digdir.Domain.Dialogporten.WebApi.Integration.Tests/Features/V1/SwaggerSnapshotTests.cs

Missing articles, prepositions, punctuation
Consolidate formatting
Consolidate spelling
Remove periods on swagger summaries (there were two, no other endpoints had them)

chore: minor cleanups

---

.azure/infrastructure/prod.bicepparam

fix(azure): ensure environment parameter for production is correct

---

.azure/applications/graphql/prod.bicepparam
.azure/applications/web-api-eu/prod.bicepparam
.azure/applications/web-api-migration-job/prod.bicepparam
.azure/applications/web-api-so/prod.bicepparam

feat(azure): add bicep parameter files for production

---

src/Digdir.Domain.Dialogporten.GraphQL/appsettings.prod.json
src/Digdir.Domain.Dialogporten.WebApi/appsettings.prod.json

Added missing configuration files for production environment. 
- #845

feat(web-api): add production config

---

README.md

* Simplify language
* GitHub capitalization
* Missing articles
* Typos

chore: README.md cleanup

---

.azure/applications/graphql/prod.bicepparam
.azure/applications/web-api-eu/prod.bicepparam
.azure/applications/web-api-so/prod.bicepparam

Adding the IP for the APIM in production as IP-restriction for the apps. 
- #845

fix(azure): use correct ip for APIM in prod

---

src/Digdir.Domain.Dialogporten.WebApi/Common/Authentication/ServiceOwnerOnBehalfOfPersonMiddleware.cs

Fixed OverrideClaim in ServiceOwnerOnBehalfOfPersonMiddleware, check for serviceproviderscope in ServiceOwnerOnBehalfOfPersonMiddleware

chore: fixed OverrideClaim, check for serviceproviderscope in middleware

---

.github/CODEOWNERS
CODEOWNERS

chore(github): add infra to codeowners

---

.github/workflows/ci-cd-main.yml

ci: remove path ignore for tests

---

.editorconfig

When auto formatting in IDE, prefer option 1:

chore(editorconfig): Prefer attribute on line above associated item

---

.azure/modules/functionApp/slackNotifier.bicep

Extended query for Slack Notifier to include traces and filter out ClientConnectionFailures (apim errors)
- #989

chore(azure): Extended query for Slack Notifier to include traces

---

src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/AltinnAuthorizationClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/DecisionRequestHelper.cs

Log error if Altinn Auth returns an "Indeterminate" decision
- #989

chore: Log error if Altinn Auth returns "Indeterminate"

---

src/Digdir.Domain.Dialogporten.GraphQL/ServiceCollectionExtensions.cs

Small performance fix, the first query when a container starts can be really slow.

chore(graphql): Initialize schema at startup

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Actors/ActorValidationErrorMessages.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommandValidator.cs

chore(webapi): Improve error message for Actor validation

---

.github/workflows/action-publish.yml

ci: build docker image for janitor

---

.github/workflows/action-deploy-apps.yml

ci: do not require migrations for job deployments

---

.github/workflows/action-deploy-apps.yml

ci: deploy jobs regardless of migration job skipped

---

src/Digdir.Domain.Dialogporten.Application/Common/Extensions/DbSetExtensions.cs
src/Digdir.Domain.Dialogporten.Application/Common/Pagination/PaginatedList.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/SearchDialogQuery.cs

Nå ble dette litt mer enn noen forslag om akkurat PRen din. Jeg så noe lavt hengende frukt i PaginatedList også som jeg håper du syns er greit at jeg bare slenger inn her 🙏

Noen forslag

---

.azure/applications/graphql/main.bicep
.azure/applications/graphql/prod.bicepparam
.azure/applications/graphql/staging.bicepparam
.azure/applications/graphql/test.bicepparam

chore(graphql): disable apim

---

tests/k6/tests/enduser/dialogSearch.js
tests/k6/tests/serviceowner/dialogCreateInvalidProcess.js
tests/k6/tests/serviceowner/dialogSearch.js

Fixed e2e with invalid URI after validation was updated

chore: fixed e2e tests

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/MappingProfile.cs

fix(webAPI): Broken mapping when creating Transmissions in an Update

---

.azure/modules/serviceBus/addDataOwnerRoles.bicep
.azure/modules/serviceBus/main.bicep

Update to use the new version of servicebus namespace

chore(servicebus): upgrade version

---

.azure/applications/service/main.bicep

Using the healthz endpoint before the proper service is deployed
- #1301

chore(service): use correct docker image

---

tests/k6/common/config.js
tests/k6/run.ps1
tests/k6/run.sh

test(e2e): ensure yt01 is an accepted environment

---

src/Digdir.Domain.Dialogporten.Service/appsettings.prod.json
src/Digdir.Domain.Dialogporten.Service/appsettings.staging.json
src/Digdir.Domain.Dialogporten.Service/appsettings.test.json
src/Digdir.Domain.Dialogporten.Service/appsettings.yt01.json

fix(service): ensure correct maskinporten environment

---

.github/workflows/ci-cd-prod.yml
.github/workflows/ci-cd-staging.yml
.github/workflows/ci-cd-yt01.yml

- Until we figure out another way, we need to use PATs for now to have access to gh variables.

ci: ensure we use correct gh token for storing versions

---

src/Digdir.Domain.Dialogporten.Infrastructure/MigrationBundle.dockerfile

chore: Move global dotnet tool installation in migration docker file

---

src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureExtensions.cs

chore(infra): Re-enable MemoryCache for authorized parties

---

docker-compose-db-redis.yml
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Common/DialogApplication.cs

chore(dev): Downgrade PostgreSQL minor version to match Azure

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogTransmissions/Search/SearchDialogTransmissionEndpoint.cs

fix(webapi): Set correct swagger return type for transmission list

---

renovate.json

Grouping by Microsoft, Npgsql, and Serillog to begin with

chore: Group NuGet upgrades in RenovateBot PRs

---

README.md

Fix some broken links in readme

chore: Fix some broken links in readme

---

.azure/applications/graphql/main.bicep
.azure/applications/service/main.bicep
.azure/applications/sync-resource-policy-information-job/main.bicep
.azure/applications/sync-subject-resource-mappings-job/main.bicep
.azure/applications/web-api-eu/main.bicep
.azure/applications/web-api-migration-job/main.bicep
.azure/applications/web-api-so/main.bicep
.github/CODEOWNERS
.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-staging.yml
.github/workflows/ci-cd-yt01.yml
README.md
src/Digdir.Domain.Dialogporten.Application/Common/Extensions/ClaimsPrincipalExtensions.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Delete/DeleteDialogCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Create/CreateDialogEndpointSummary.cs
src/Digdir.Tool.Dialogporten.GenerateFakeData/DialogGenerator.cs
tests/Digdir.Domain.Dialogporten.WebApi.Integration.Tests/Features/V1/SwaggerSnapshotTests.cs
tests/k6/tests/enduser/performance/README.md
tests/k6/tests/graphql/performance/README.md
tests/k6/tests/serviceowner/performance/README.md

chore: rename organization name to altinn

---

src/Digdir.Domain.Dialogporten.GraphQL/Program.cs
src/Digdir.Domain.Dialogporten.Service/Program.cs

Missing calls to OpenTelemetryExtensions

fix(app): Add missing telemetry setup GraphQL and Service

---

src/Digdir.Domain.Dialogporten.Janitor/Common/Extensions/OpenTelemetryExtensions.cs
src/Digdir.Domain.Dialogporten.Janitor/Digdir.Domain.Dialogporten.Janitor.csproj
src/Digdir.Domain.Dialogporten.Janitor/Program.cs

feat(janitor): add otlp logger for janitor

---

src/Digdir.Domain.Dialogporten.Application/Common/Behaviours/ValidationBehaviour.cs
tests/k6/tests/serviceowner/dialogCreateInvalidActionCount.js

chore(ci): Fix e2e test after create comand refactoring

---

src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureExtensions.cs

chore(service): Use ConsoleLogEventBus in yt01

---

src/Digdir.Domain.Dialogporten.ChangeDataCapture/Digdir.Domain.Dialogporten.ChangeDataCapture.csproj
src/Digdir.Domain.Dialogporten.GraphQL/Digdir.Domain.Dialogporten.GraphQL.csproj
src/Digdir.Domain.Dialogporten.Infrastructure/Digdir.Domain.Dialogporten.Infrastructure.csproj
src/Digdir.Domain.Dialogporten.WebApi/Digdir.Domain.Dialogporten.WebApi.csproj
src/Digdir.Library.Utils.AspNet/Digdir.Library.Utils.AspNet.csproj
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Digdir.Domain.Dialogporten.Application.Integration.Tests.csproj

chore(deps): Remove unnecessary explicit NuGet-refs

---

.azure/applications/service/main.bicep
.azure/applications/service/prod.bicepparam
.azure/applications/service/staging.bicepparam
.azure/applications/service/test.bicepparam
.azure/applications/service/yt01.bicepparam

Adjusting the sample rate for `service`. Too many log entries in `yt01` at the moment. 
- #N/A

fix(service): Avoid too many logs in app insights

---

src/Digdir.Domain.Dialogporten.GraphQL/Common/Authentication/LocalDevelopmentUser.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Authorization/AuthorizationPolicy.cs

Forgot this in the last PR, using "docs" so it does not show up in the change log twice 😇 🙈 
- #1743

fix(graphql): Use correct type filter for LocalDevelopmentUser 

---

docs/schema/V1/schema.verified.graphql
docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Events/CloudEventTypes.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Activities/DialogActivityType.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/Common/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20250127115234_AddFormSubmittedAndFormSavedToActivityType.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20250127115234_AddFormSubmittedAndFormSavedToActivityType.cs

chore: Add FormSubmitted and FormSaved to ActivityType

---

src/Digdir.Domain.Dialogporten.WebApi/DelayedShutdownHostLifetime.cs
src/Digdir.Domain.Dialogporten.WebApi/Program.cs

Adjusting shutdown delay. Ref discussion in this thread: https://digdir.slack.com/archives/C07R312076E/p1738364898052139
Plucked from this blogpost: https://github.com/dotnet/dotnet-docker/blob/main/samples/kubernetes/graceful-shutdown/graceful-shutdown.md#adding-a-shutdown-delay
- #N/A

fix(web-api): ensure graceful shutdown

---

src/Digdir.Domain.Dialogporten.Infrastructure/MigrationBundle.dockerfile

GitHub Action has a timeout defined

fix: Disable efbundle migration timeout

---

docker-compose-otel.yml

Running different major version locally in docker compose setup, this downgrades to match what we have in Azure

chore(dev): Downgrade local Grafana to match Azure version

---

Digdir.Domain.Dialogporten.sln
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/.editorconfig
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/.gitignore
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/CopyTaskDto.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/DeterministicUuidV7.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/Digdir.Tool.Dialogporten.LargeDataSetGenerator.csproj
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/Activity.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/Actor.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/Attachment.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/AttachmentUrl.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/Dialog.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/DialogContent.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/EndUserContext.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/GuiAction.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/Localization.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/LocalizationSet.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/SearchTags.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/SeenLog.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/Transmission.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/EntityGenerators/TransmissionContent.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/Parties.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/Program.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/Properties/launchSettings.json
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/README.md
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/SeedDatabaseDto.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/Sql.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/Words.cs
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/recreate-indexes.sh
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/runner.sh
src/Digdir.Tool.Dialogporten.LargeDataSetGenerator/service_resources

chore(yt01): Large data set generator

---

.github/workflows/ci-cd-prod.yml

ci: ensure we check the correct tag in prod workflow

---

.github/workflows/ci-cd-yt01.yml

Added some permissions
- #1862

chore(performance): Add correct permissions to ci-cd-yt01

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Events/AltinnForwarders/DialogEventToAltinnForwarder.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Events/CloudEventTypes.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Transmissions/DialogTransmission.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Events/DialogTransmissionCreatedDomainEvent.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Common/Events/DomainEventsTests.cs
tests/Digdir.Domain.Dialogporten.Application.Unit.Tests/Features/V1/Common/Utils/ApplicationEventHandlerUtilsTests.Developer_Should_Use_Caution_When_Modifying_Endpoints.verified.txt
tests/Digdir.Domain.Dialogporten.Application.Unit.Tests/Features/V1/Common/Utils/ApplicationEventHandlerUtilsTests.Developer_Should_Use_Caution_When_Modifying_Events.verified.txt

feat: Add event for transmission created

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogDto.cs

feat: Allow setting Process/PrecedingProcess in dialog updates

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogSystemLabels/Commands/Set/SystemLabelCommand.cs
src/Digdir.Domain.Dialogporten.GraphQL/Common/Constants.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/MutationTypes/Mutations.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogSystemLabels/Set/SetDialogSystemLabelEndpoint.cs

fix: Return new revision ETag on system label update

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Patch/PatchDialogsController.cs

fix(webapi): Return 410 GONE for deleted dialogs on patch endpoint

---

src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Patch/PatchDialogsController.cs

fix(webapi): Add missing query param for disabling Altinn events to patch endpoint

---

.github/workflows/ci-cd-yt01.yml

Remove warm-up step before performance, e2e-test should be enough
- #1862

chore(performance): remove warm-up step before performance tests

---

.github/workflows/workflow-check-for-changes.yml
src/Digdir.Library.Dialogporten.WebApiClient/README.md

ci: fix check for changes for web api client

---

tests/k6/common/sentinel.js

Fix cleanup after e2e-tests
- #

chore(e2e): put filter on createdAfter for search in cleanup-step e2e-tests

---

.github/workflows/ci-cd-prod.yml

An issue where deployment and migration were run regardless of files changed since last version. Some changes that were left behind after the refactor
- #N/A

ci: ensure we deploy infra and apps only when necessary

---

.gitignore

Used for Cursor-related configuration like cursor rules: `.cursor/rules/example.mdc`
https://docs.cursor.com/context/rules-for-ai
- #N/A

trivial: add .cursor to gitignore

---

docs/schema/V1/package-lock.json
docs/schema/V1/package.json

Updated vitest and esbuild to mitigate a vulnerability in esbuild 0.24.2

chore(deps): update vitest to 3.0.7 and esbuild to 0.25.0

---

docs/schema/V1/schema.verified.graphql
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/Parties/ObjectTypes.cs

chore(graphql): Remove HasOnlyAccessToSubParties from sub-party

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.WebApi/Program.cs

fix(webapi): Move swagger server override to correct post processing step

---

tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Common/DialogApplication.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Common/Events/DomainEventsTests.cs

These tests fail randomly
This is caused by many layers of async with MassTransit harness and mediator
Simplifying these tests by removing MassTransit consumption/converting to cloud events.
These tests will only check if domain events of the correct type is created.
Will add another set of tests for cloud event conversions.
- #2044

fix(test): Simplify domain event tests, remove MassTransit harness

---

.github/workflows/ci-cd-yt01.yml

trivial: Add temp workflow call to yt01 workflow

---

tests/k6/common/config.js

test: ensure we use the correct env for test

---

.azure/modules/virtualMachine/main.bicep

fix(infra): fix JIT for ssh-jumpers

---

scripts/database-forwarder/forward.sh

* Added JIT access as a part of the script. This will open up port `22`  for 1 hour to your public ip address. 
- #1995

chore(database-forwarder): enhance security with JIT and some refactors

---

.azure/modules/virtualMachine/main.bicep

24 hours is a bit much. Using 1 hour in the script. This should probably be adjusted per environment, but setting 8 hours for now. 
- #1995

fix(infra): decrease time to 8 hours for jit requests

---

.github/workflows/ci-cd-yt01.yml
tests/k6/common/k6-utils.js
tests/k6/tests/graphql/performance/README.md
tests/k6/tests/graphql/performance/graphql-search.js
tests/k6/tests/graphql/performance/graphqlSearchWithThresholds.js
tests/k6/tests/performancetest_common/simpleSearch.js

Do graphql search like AF does
Add graphql threshold tests to CI/CD for yt01
Updated graphql readme
- #2092 
- #2094

chore(performance): improved graphql search and added graphql threshold tests to ci/cd yt01

---

.github/actions/build-schema/action.yml
.github/workflows/ci-cd-pull-request.yml
.github/workflows/workflow-check-for-changes.yml
.github/workflows/workflow-publish-schema.yml
docs/schema/V1/README.md

- Ensure that we build the schema package if we change some files in it
- Move the install, build and test of schema into a composite action
- #N/A

ci: ensure we build the schema package on prs

---

.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-prod.yml
.github/workflows/ci-cd-staging.yml
.github/workflows/ci-cd-yt01.yml
.github/workflows/workflow-swarmia-deployment.yml

ci: ensure we send version to swarmia

---

.github/actions/azure-login/action.yml
.github/actions/build-schema/action.yml
.github/workflows/ci-cd-pull-request-release-please.yml
.github/workflows/ci-cd-pull-request-title.yml
.github/workflows/ci-cd-release-please.yml
.github/workflows/workflow-build-and-test.yml
.github/workflows/workflow-build-infrastructure.yml
.github/workflows/workflow-check-for-changes.yml
.github/workflows/workflow-delete-deployments.yml
.github/workflows/workflow-deploy-apps.yml
.github/workflows/workflow-deploy-infra.yml
.github/workflows/workflow-publish-nuget.yml
.github/workflows/workflow-publish-schema.yml
.github/workflows/workflow-publish.yml
.github/workflows/workflow-run-k6-performance.yml
.github/workflows/workflow-run-k6-tests.yml
.github/workflows/workflow-send-ci-cd-status-slack-message.yml

chore(ci): Use step-security/harden-runner

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommandValidator.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/CreateDialogTests.cs

fix(webapi): Allow default(DateTimeOffset) for CreatedAt and UpdatedAt

---

.github/actions/build-schema/action.yml

https://github.com/Altinn/dialogporten/actions/runs/14269487948/job/39999203858?pr=2168

ci: Remove harden-runner from build schema action

---

.github/workflows/workflow-deploy-apps.yml
.github/workflows/workflow-deploy-infra.yml

ci: Change arm-deploy to bicep-deploy

---

.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-prod-dry-run.yml
.github/workflows/ci-cd-prod.yml
.github/workflows/ci-cd-pull-request-release-please.yml
.github/workflows/ci-cd-pull-request.yml
.github/workflows/ci-cd-staging.yml
.github/workflows/ci-cd-yt01.yml
.github/workflows/dispatch-apps.yml
.github/workflows/workflow-deploy-apps.yml
.github/workflows/workflow-deploy-infra.yml

ci: Fix bicep-deploy

---

tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/UniqueConstraintTests.cs

test: Add tests for unique constraints on Ids/IdempotentKey

---

.azure/infrastructure/main.bicep
.azure/infrastructure/prod.bicepparam
.azure/infrastructure/staging.bicepparam
.azure/infrastructure/test.bicepparam
.azure/infrastructure/yt01.bicepparam
.azure/modules/containerAppEnv/main.bicep

Enable HA for Container App Environment for `staging` and `prod`. This requires recreation of the container app environment. 
- #2133

feat(infra): enable HA for container app envs

---

src/Digdir.Tool.Dialogporten.GenerateFakeData/DialogGenerator.cs
src/Digdir.Tool.Dialogporten.GenerateFakeData/Program.cs

* Greatly improve performance (from ~170 dialogs/sec to ~15000 dialogs/sec on a M3 Pro)
* Added simple support for adding a Authorization header given a token from the command line
* Added support for pre-generating request DTOs, that can be used for external load tools (siege etc)
* Show current dialogs/sec as well as total (to account for JIT delays in generator code)
* Maintains existing API (as used by integration tests), ie. not a rewrite as indicated by #1123
- N/A

chore: Improve dialog generator

---

.azure/modules/postgreSql/create.bicep

chore(infra): Set Postgres idle transacion timeout

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogSystemLabels/Commands/Set/SetDialogSystemLabelCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogSystemLabels/Commands/Set/SetSystemLabelCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogSystemLabels/Commands/Set/SystemLabelDto.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/MutationTypes/MappingProfile.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/MutationTypes/Mutations.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogSystemLabels/Set/SetDialogSystemLabelEndpoint.cs
tests/k6/tests/enduser/dialogSystemLabelLog.js

fix(webapi): Move set label revision from body to If-Match header

---

tests/k6/tests/all-tests.js
tests/k6/tests/serviceowner/dialogSearch.js

fix(e2e): Add missing params on search test

---

docker-compose-db-redis.yml
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Common/DialogApplication.cs

Matching deployed version in Azure

test: Upgrade postgres image tag to 16.8

---

src/Digdir.Library.Utils.AspNet/Digdir.Library.Utils.AspNet.csproj

Reverts Altinn/dialogporten#2253

trivial: revert "update dependency opentelemetry.exporter.opentelemetryprotocol to 1.12.0"

---

README.md

- fix typo for Docker Compatibility mode in README

trivial: Fix Docker compatibility typo

---

.azure/applications/sync-resource-policy-information-job/main.bicep
.azure/applications/sync-subject-resource-mappings-job/main.bicep
.azure/applications/web-api-migration-job/main.bicep
.azure/modules/containerAppJob/main.bicep

We create user-assigned identity for the jobs. There is some weird behaviour for the container app jobs now relating to secrets. This might be the underlying issue..
- #N/A

fix(infra): ensure correct permissions to key vault from jobs

---

AGENTS.md

Adding AGENTS.md to provide context for AI coding agents.

chore: Add AGENTS.md

---

.azure/infrastructure/main.bicep
.azure/modules/vnet/main.bicep

Leftover from adding workload profiles
- #2257

fix(infra): remove conditional delegation on vnet

---

tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/DialogSystemLabels/BulkSetDialogSystemLabelTests.cs

- verify bulk label update when enduser context revisions match
- `dotnet build Digdir.Domain.Dialogporten.sln -c Release`
- `dotnet test Digdir.Domain.Dialogporten.sln -c Release` *(fails: Testcontainers cannot run without Docker)*

test(serviceowner): add revision match bulk set test

---

.azure/modules/appConfiguration/create.bicep

fix(infra): ensure diagnostic setting is set correctly for app config

---

.azure/modules/postgreSql/create.bicep

Create the admin identity for the postgresql server. This is the first step to create the actual admin user to be used to add the user assigned identities for the apps later. 
- #2171

feat(infra): managed identity admin user for postgresql

---

.azure/modules/ssh-jumper/main.bicep
.azure/modules/virtualMachine/main.bicep

Solving one of the security recommendations, enabling encryption at host: https://learn.microsoft.com/en-us/azure/virtual-machines/disks-enable-host-based-encryption-portal?tabs=azure-powershell
- #2320

feat(infra): add encryption at host for virtual machines

---

.azure/applications/service/main.bicep
.azure/applications/sync-resource-policy-information-job/main.bicep
.azure/applications/sync-subject-resource-mappings-job/main.bicep
.azure/applications/web-api-eu/main.bicep
.azure/applications/web-api-migration-job/main.bicep
.azure/applications/web-api-so/main.bicep

This ensures that the dependencies are created before the actual app. 
- #N/A

chore(apps): ensure role assignments are created before capp

---

docs/schema/V1/schema.verified.graphql
docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/DialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/DialogDtoBase.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Common/DialogStatuses/DialogStatusInput.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Common/DialogStatuses/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/DialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/DialogDtoBase.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/DialogStatus.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/Common/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20250623133933_ReAssignDialogStatusValues.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20250623133933_ReAssignDialogStatusValues.cs
src/Digdir.Domain.Dialogporten.Infrastructure/UnitOfWork.cs
src/Digdir.Library.Dialogporten.WebApiClient/Features/V1/RefitterInterface.cs
src/Digdir.Tool.Dialogporten.GenerateFakeData/DialogGenerator.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Queries/GetDialogTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Queries/Search/SearchDialogTests.cs

feat(revert): Support old enum values for dialog status

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/Validators/CreateDialogDialogTransmissionDtoValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogDataLoader.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/Validators/UpdateDialogDialogTransmissionDtoValidator.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Common/CreateDialogCommandExtensions.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Common/UpdateDialogCommandExtensions.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Transmissions/Commands/UpdateTransmissionTests.cs

fix(app): Check existing TransmissionAttachment ids on update

---

src/Digdir.Domain.Dialogporten.Infrastructure/UnitOfWork.cs

fix(app): ReferenceConstraintException race condition

---

docs/schema/V1/schema.verified.graphql
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/SearchDialogs/ObjectTypes.cs

fix(graphql): Add missing ContentUpdatedAt mapping on search DTO

---

src/Digdir.Domain.Dialogporten.GraphQL/Program.cs
src/Digdir.Domain.Dialogporten.Service/Program.cs
src/Digdir.Domain.Dialogporten.WebApi/Program.cs

Removes the slightly annoying delayed shutdown in dev (as it is only relevant in scale-in scenarios)

chore: Disable delayed shutdown in dev

---

src/Digdir.Domain.Dialogporten.Application/Externals/AltinnAuthorization/AuthorizedPartiesResult.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/AltinnAuthorizationClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/AuthorizedPartiesResultDto.cs

fix(): Parsing error for AuthorizedInstances, add AuthorizedResource

---

tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/UpdateDialogTests.cs

test: fixed DialogUpdateTests fails randomly

---

src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureExtensions.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/FusionCache/FusionCacheWarmupHostedService.cs

fix: Add warm up service for FusionCache

---

tests/k6/tests/enduser/dialogSystemLabelLog.js
tests/k6/tests/serviceowner/dialogSystemLabels.js

test(e2e): Fix SystemLabel tests after #2588

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/EndUserContext/Commands/SetSystemLabel/SetSystemLabelCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/EndUserContext/Commands/SetSystemLabels/SetSystemLabelCommand.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Common/ApplicationFlow/IFlowStepExtensions.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/EndUser/SystemLabels/Commands/SetSystemLabelTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/SystemLabels/Commands/SetSystemLabelTests.cs

test: extensions and tests for markedAsUnopened

---

src/Digdir.Domain.Dialogporten.Application/LocalDevelopmentSettings.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/NameRegistry/PartyNameRegistryClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureExtensions.cs
src/Digdir.Domain.Dialogporten.WebApi/appsettings.Development.json
src/Digdir.Library.Dialogporten.WebApiClient/Features/V1/RefitterInterface.cs

fix(local-dev): Created LocalPartyNameRegistry

---

.github/workflows/ci-cd-yt01.yml

trivial(ci): Disable yt01 deployments

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Common/DialogStatuses/DialogStatusInput.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/Validators/CreateDialogDtoValidator.cs
src/Digdir.Domain.Dialogporten.WebApi/OpenApiDocumentExtensions.cs
src/Digdir.Domain.Dialogporten.WebApi/Program.cs
src/Digdir.Library.Dialogporten.WebApiClient/Features/V1/RefitterInterface.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/CreateDialogTests.cs

feat(webapi): Make Status nullable when creating dialogs

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogQuery.cs

fix(app): Catch AutoMapper exceptions on get/purge race condition

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/EndUserContext/Queries/SearchLabelAssignmentLogs/SearchDialogLabelAssignmentLogEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/ServiceOwnerContext/Queries/GetServiceOwnerLabel/GetServiceOwnerLabelEndpointSummary.cs
src/Digdir.Library.Dialogporten.WebApiClient/Features/V1/RefitterInterface.cs

chore(webapi): Add Swagger summary for label assignment log endpoint

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogQuery.cs

trivial: Remove try-catch for missing labels edge case

---

src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/DialogEntity.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/CreateDialogTests.cs

fix(app): Set ContentUpdatedAt to UpdatedAt on create

---

.github/workflows/ci-cd-release-please.yml

Release please suddenly stopped working. Background: https://digdir.slack.com/archives/C079D6PAGDS/p1755860434350869?thread_ts=1755595462.906849&cid=C079D6PAGDS
Updating to new version which contains the fix. 
- #N/A

fix(release-please): update new version of release please

---

src/Digdir.Domain.Dialogporten.Application/Common/Extensions/FluentValidation/FluentValidationUuiDv7Extensions.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/CreateDialogTests.cs

fix(app): Add tolerance when validating uuidv7 timestamps

---

.azure/modules/postgreSql/create.bicep

fix(infra): use correct role and tag

---

src/Digdir.Domain.Dialogporten.GraphQL/Digdir.Domain.Dialogporten.GraphQL.csproj
src/Digdir.Domain.Dialogporten.Infrastructure/Digdir.Domain.Dialogporten.Infrastructure.csproj

This reverts commit c748cdab89a5bb42248be7a4326487c092648af1.

trivial: Revert "chore(deps): update hotchocolate monorepo to 15.1.10 (#2731)"

---

.azure/infrastructure/prod.bicepparam

Still at 1GB in memory. Not seeing the need to upgrade here based on the metrics so far. 
- #2184

chore(infra): upgrade SKU for redis to Standard in production

---

tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/LanguageCodes/LanguageCodeTests.cs

suggestion: backward compatibility test language codes

---

docs/schema/V1/schema.verified.graphql
src/Digdir.Domain.Dialogporten.GraphQL/IRequestExecutorBuilderExtensions.cs
src/Digdir.Domain.Dialogporten.GraphQL/ServiceCollectionExtensions.cs

fix(graphql): Add missing SetSystemLabel errors to schema

---

src/Digdir.Library.Utils.AspNet/HealthCheckFilter.cs
src/Digdir.Library.Utils.AspNet/OpenTelemetryExtensions.cs

- Check if Path ends with `/health` instead of starts with do avoid issues with APIM
- https://github.com/Altinn/altinn-dialogporten-adapter/issues/52

chore(otel): Disable health check tracing

---

src/Digdir.Domain.Dialogporten.Application/Common/Behaviours/FeatureMetric/FeatureMetricBehaviour.cs
src/Digdir.Domain.Dialogporten.Application/Common/Behaviours/FeatureMetric/FeatureMetricRecorder.cs
src/Digdir.Domain.Dialogporten.Application/Common/Behaviours/FeatureMetric/LoggingFeatureMetricDeliveryContext.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Common/IntegrationTestUser.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Common/Behaviours/FeatureMetricEndToEndTests.cs

fix(app): Use org consumer claim for feature metrics

---

.azure/applications/graphql/main.bicep
.azure/applications/graphql/prod.bicepparam
.azure/applications/graphql/staging.bicepparam
.azure/applications/graphql/test.bicepparam
.azure/applications/graphql/yt01.bicepparam
.azure/applications/web-api-eu/main.bicep
.azure/applications/web-api-eu/prod.bicepparam
.azure/applications/web-api-eu/staging.bicepparam
.azure/applications/web-api-eu/test.bicepparam
.azure/applications/web-api-eu/yt01.bicepparam
.azure/applications/web-api-so/main.bicep
.azure/applications/web-api-so/prod.bicepparam
.azure/applications/web-api-so/staging.bicepparam
.azure/applications/web-api-so/test.bicepparam
.azure/applications/web-api-so/yt01.bicepparam
src/Digdir.Library.Utils.AspNet/OpenTelemetryExtensions.cs

trivial(app): remove OTEL environment variables

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Content/ContentValueDtoValidator.cs
tests/Digdir.Domain.Dialogporten.Application.Unit.Tests/Features/V1/ServiceOwner/Dialogs/Validators/ContentValueDtoValidatorTests.cs

trivial(app): use existing correspondence scope constant
