Altinn/dialogporten

src/Digdir.Domain.Dialogporten.Application/Features/V1/Dialogs/Commands/Update/UpdateDialogCommand.cs

Fix issue where new element with client defined ID is marked as updated and not created as it should.

Mark new client defined ID DialogElement as created

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Localizations/LocalizationDtoValidator.cs
src/Digdir.Domain.Dialogporten.Domain/Localizations/Localization.cs

Har lagt til validering av culture code. Vi aksepterer både '-' og '_' som separator og er case insensitive og tåler trailing og leading whitespace.
Applikasjonen vil konsolidere formatene. Dersom en bruker sender inn 'en_gb', en annen sender inn 'en-gb    ', og en tredje sender inn 'en-GB' vil alle passere valideringsregelen og referere til den samme kulturen, og bli lagret som 'en-gb'?
De aksepterte kulturene hentes ut fra .nets System.Globalization.CultureInfo. Under er en fil med gyldige kultur strenger:
[SupportedCultures.txt](https://github.com/digdir/dialogporten/files/11881529/SupportedCultures.txt)

Add culture code validation

---

src/Digdir.Domain.Dialogporten.Application/Common/Extensions/FluentValidation/FluentValidation_Enumerable_Extensions.cs
src/Digdir.Domain.Dialogporten.WebApi/Program.cs
src/Digdir.Library.Entity.Abstractions/Digdir.Library.Entity.Abstractions.csproj
src/Digdir.Library.Entity.Abstractions/Features/Identifiable/IdentifiableExtensions.cs

* Use Medo.Uuid7 instead of UuidNext. Medo.Uuid7 generates uuids in sequence, even within the same ms. The idea is to give a better integration experiance by returning items in the arrays in the same order they were added to the API.
* Fix a bug where the FluentValidation extension `UniqueBy` did not allow default key values. That is - if the user inputs two items in the same array without specifying id, effectively saying to the API "please generate the ids for me", `UniqueBy` would invalidate the request. 
* Use SwaggerDocument instead of deprecated FastEndpoint `AddSwaggerDoc` method.

Use Medo.Uuid7 guid generator

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogActivities/Queries/Get/GetDialogActivityDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogActivities/Queries/Get/GetDialogActivityQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogActivities/Queries/Get/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogActivities/Queries/List/ListDialogActivityDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogActivities/Queries/List/ListDialogActivityQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogActivities/Queries/List/MappingProfile.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogActivity/GetDialogActivityEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogActivity/ListDialogActivityEndpoint.cs

Skal vi ha med deleted-info om parent dialog her? 
Har mapped `element.dialog.DeletedAt` til en property `DialogDeletedAt` på DTOen
For lista blir det kanskje litt weird å ha den på alle:
```json
[
{
"id": "59178a01-9617-3d76-93ae-4586beb6ab25",
"createdAt": "2023-08-21T09:07:09.3361090Z",
"type": "Submission",
"dialogDeletedAt": "2023-08-21T09:10:35.2590080Z"
},
{
"id": "59178a01-9617-3d76-93b4-6845191b68cc",
"createdAt": "2023-08-21T09:07:09.3361090Z",
"type": "Submission",
"dialogDeletedAt": "2023-08-21T09:10:35.2590080Z"
}
]
```
Kan ev. flytte activities et nivå ned? 
```json
{
"dialogDeletedAt": "2023-08-21T09:10:35.2590080Z",
"activities": [
{
"id": "59178a01-9617-3d76-93ae-4586beb6ab25",
"createdAt": "2023-08-21T09:07:09.3361090Z",
"type": "Submission"
},
{
"id": …
```

Add GET dialog activities for service owners

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/List/ListDialogQuery.cs
tests/k6/common/console.js
tests/k6/common/describe.js
tests/k6/common/dialog.js
tests/k6/common/k6chai.js
tests/k6/common/request.js
tests/k6/common/testimports.js
tests/k6/tests/enduser/all-tests.js
tests/k6/tests/serviceowner/all-tests.js
tests/k6/tests/serviceowner/authorization.js
tests/k6/tests/serviceowner/dialogCreateInvalidActionCount.js
tests/k6/tests/serviceowner/dialogCreatePatchDelete.js
tests/k6/tests/serviceowner/dialogSearch.js
tests/k6/tests/serviceowner/performance/createremove-no-delay.js
tests/k6/tests/serviceowner/testdata/01-create-dialog.js

* Adds utility functions
* For manipulating dialog DTOs before submitting (`setTitle`, `setExtendedStatus` etc)
* `console.dir` for printing objects (not implemented in Goja/K6)
* `expectStatusFor(respo).to.equal(200)` as shorthand for `expect(response, "response status").to.equal(200)`, which also displays additional info if an error details reponse 
* Added `hasLocalizedText` extension to Chai, eg. `expect(r.json().items[0], 'first dialog').to.have.property("title").that.hasLocalizedText("some title", "nb_NO");  /* cultureCode optional */`
* Handles serialization of DTOs in request.js, if necessary (no need to remember it at callsite)
* Add search in "body" in dialogs (will be replaced in #215)

More search tests + fix body searching

---

src/Digdir.Domain.Dialogporten.Application/Common/Extensions/ClaimsPrincipalExtensions.cs
src/Digdir.Domain.Dialogporten.Application/Common/IUserService.cs
src/Digdir.Domain.Dialogporten.Application/Externals/IOrganizationRegistry.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommand.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/DialogEntity.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/OrganizationRegistry/OrganizationRegistryClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/ResourceRegistry/LocalDevelopmentResourceRegistry.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/ResourceRegistry/ResourceRegistryClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureExtensions.cs
src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureSettings.cs
src/Digdir.Domain.Dialogporten.WebApi/appsettings.Development.json
src/Digdir.Domain.Dialogporten.WebApi/appsettings.json

Fix #293
-Populerer Org på DialogEntity fra token hvis det eksisterer
-Henter Org verdi fra altinncdn eller distributedcache hvis det ikke eksisterer i token
Co-authored by Are Almaas, Magnus Sandgren

Populer DialogEntity.Org fra token eller http/distributedcache

---

src/Digdir.Domain.Dialogporten.ChangeDataCapture/Dockerfile
src/Digdir.Domain.Dialogporten.Infrastructure/MigrationBundle.dockerfile
src/Digdir.Domain.Dialogporten.Service/Dockerfile
src/Digdir.Domain.Dialogporten.WebApi/Dockerfile
src/Digdir.Tool.Dialogporten.MigrationVerifier/Dockerfile

Issue: #325 
- Mistenker at det er dette som forårsaker at vi må restore for hvert bygg. Tror ikke string interpolation er så godt støttet. Med denne er vi mer verbose, men også mer eksplisitt på hva vi drar inn i Dockerfilen. Kan også optimaliseres med å kun kopiere inn relevante prosjekter istedenfor hele `src`-mappen. 
- Satte også `sha` til hvert image slik at vi vet at vi bruker samme versjon av `8.0` inntil vi velger å oppgradere det på et tidspunkt

chore(Dockerfiles): avoid busting cache on each build

---

.azure/.test.bicepparam
.azure/apim/create.bicep
.azure/appConfiguration/create.bicep
.azure/applicationInsights/create.bicep
.azure/functionApp/slackNotifier.bicep
.azure/keyvault/create.bicep
.azure/main.bicep
.azure/postgreSql/create.bicep

Issue: #303 
Parameterisering av SKUer. Blir litt mange parametre, men blir. også veldig fleksibelt per miljø.

feat(azure): parameterize SKUs

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/SearchDialogQueryValidator.cs

Når det når det søkes med feil EndUserId-filtrering på SO-APIet er propertynavnet blankt

bug: Fix EnduserId validation message when searching

---

.github/workflows/action-deploy-apps.yml
.github/workflows/action-deploy-infra.yml

Deployments are failing because of warnings about Bicep cli upgrades. That's a tad too harsh.. But there doesn't seem to be a way to disable just those types of warnings so we rather skip failing on warnings. Need to add a different build step to catch these warning instead. Like a validation deployment or something similar. 
https://github.com/Azure/arm-deploy/issues/126

ci: avoid failing on warnings from deployment

---

.azure/modules/containerAppJob/main.bicep
.github/tools/README.md

`Secret names cannot be longer than 20. Please shorten dialogdbconnectionstringsecreturi`
🤷

fix: shorten secret name for container app job

---

.github/workflows/ci-cd-main.yml

Ensure that we only run one workflow at the time when running the main workflow to avoid potential conflicts and race conditions

ci: queue jobs on main

---

.github/workflows/action-deploy-apps.yml
src/Digdir.Domain.Dialogporten.Infrastructure/MigrationBundle.dockerfile

- We are still struggling with the migration job not being able to run because of corrupt state in secrets for the job. Ongoing discussion with the Azure team about his issue. Enabling it for staging until it is fixed so we can verify it's working there
- Removing the logging of the connection string for the migration job 🤫

ci: enable migration job in staging

---

.azure/applications/web-api-eu/main.bicep
.azure/applications/web-api-eu/staging.bicepparam
.azure/applications/web-api-eu/test.bicepparam
.azure/applications/web-api-so/main.bicep
.azure/applications/web-api-so/staging.bicepparam
.azure/applications/web-api-so/test.bicepparam
.azure/modules/containerApp/main.bicep

APIM is set up and we want to restrict incoming requests to the APIM IP to close them down for public access.

fix: restrict container apps to apim ip

---

.github/workflows/action-deploy-apps.yml
.github/workflows/ci-cd-main.yml

- Disables the migration job in staging. OJ migrated data manually in staging
- Add `!cancelled()` to skip the jobs if we cancel the workflow

ci: disable migration job in staging

---

src/Digdir.Domain.Dialogporten.Application/Common/ReturnTypes/BadRequest.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Extensions/EndpointExtensions.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogActivities/CreateDialogActivityEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogElements/CreateDialogElementEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogElements/DeleteDialogElementEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogElements/UpdateDialogElementEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/PatchDialogsController.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/UpdateDialogEndpoint.cs

Updating/patching a deleted dialog should not return 404
(This also applies to return types for adding/removing elements, or activities, on a deleted dialog)

fix: Return 410 Gone when updating deleted dialog

---

.github/workflows/action-publish.yml
.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-staging.yml

- We don't want to overwrite the `main`-tag of the docker image each time a publish happens in either branch. 
- Fix some workflow issues for staging

fix: remove main-tag when tagging docker images

---

.github/workflows/ci-cd-main.yml

The GITHUB_TOKEN will not be able to trigger any github action runs, therefore we need to create a custom PAT to use. 
https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#github-credentials

fix(release-please): use correct gh token

---

.github/workflows/action-deploy-infra.yml
.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-staging.yml
.github/workflows/dispatch-infrastructure.yml

* Add version as a input value for deploying to infrastructure
* Refactor the dependencies for deploying code and infrastructure. This  makes sure that infrastructure is always deployed before backend code. If there are no changes in Azure, the backend code will still be deployed.

ci: refactor and add manual dispatch version

---

.github/workflows/action-deploy-apps.yml
.github/workflows/action-deploy-infra.yml

Fixes an issue where infra and app deployment shared the same concurrency group. One cancelling the other.

ci: fix concurrency issues in release-prs

---

.github/workflows/ci-cd-main.yml

A new fine grained PAT was generated in the digdir organization. Using that instead of my personal PAT.

ci: use new fine grained PAT for release-please

---

.github/workflows/action-deploy-apps.yml

Getting this error when trying to deploy apps:
https://github.com/digdir/dialogporten/actions/runs/8170065128/job/22338884530
```shell
Error: ERROR: {"status":"Failed","error":{"code":"DeploymentFailed",
"target":"/subscriptions/***/resourceGroups/***/providers/Microsoft.Resources/deployments/dp-be-test-web-api-eu-1.0.4-2a8fa76",
"message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.",
"details":
[{"code":"Conflict",
"message":"The resource '/subscriptions/***/resourceGroups/***/providers/Microsoft.Cache/Redis/***' 
is busy processing a previous update request or is undergoing system maintenance.  
As such, it is currently unable to accept the update request. …
```

ci(azure): avoid ARM deployment conflicts for apps

---

.azure/applications/web-api-migration-job/staging.bicepparam
.azure/applications/web-api-migration-job/test.bicepparam

Reformatting and remove `REDIS_NAME` from `staging.bicepparam`

chore: remove unused param from migration job

---

.azure/infrastructure/main.bicep

Related to https://github.com/digdir/dialogporten/issues/275
Ref new cleaner entries in appsettings: https://github.com/digdir/dialogporten/pull/527/files#diff-c6838c6aab1b032787194ad73ad63002ecd89d413a405fc7b6315572bfd97417

fix(azure): rename connection string key for redis

---

src/Digdir.Domain.Dialogporten.WebApi/Common/Authentication/AuthenticationBuilderExtensions.cs

Due to slightly mismatched clocks, tokens from the tokengenerator (or other sources) might create tokens that are not yet valid (when validation `iat` claim) in Dialogporten. We can alleviate this by allowing for 2 seconds of skew.

fix: Allow for 2 seconds clock skew in token validation

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/MappingProfile.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/Dialogs/GetDialogEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/GetDialogEndpoint.cs

The field indication dialog revision should be called "Revision" in the DTO, and only be called "IfMatchDialogRevision" in the commands.

fix: Change IfMatchDialogRevision to Revision in DTO

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Purge/PurgeDialogCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Purge/PurgeDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/PurgeDialogEndpoint.cs
src/Digdir.Library.Entity.EntityFrameworkCore/Features/Aggregate/AggregateExtensions.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Common/Events/DomainEventsTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Dialogs/Commands/PurgeDialogTests.cs

This validates the GUID input on purge commands so that we get a 400 error, instead of 500, when posting bad GUIDs.
(The error will always say "DialogId cannot be 00000...", and not "invalid JSON"  .. but better than nothing)

suggestion: validate purge command input

---

.azure/modules/redis/main.bicep

The prefix/protocol `redis://` confuses the Redis library, giving weird error messages. It expects a connection string without that prefix.

fix: remove prefix for redis connection string

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Purge/PurgeDialogCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Purge/PurgeDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/PurgeDialogEndpoint.cs
src/Digdir.Library.Entity.EntityFrameworkCore/Features/Aggregate/AggregateExtensions.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Common/Events/DomainEventsTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Dialogs/Commands/PurgeDialogTests.cs

fix: purge should accept any content-type and no body

---

.azure/modules/redis/main.bicep

We have disabled non SSL port for Redis, so have to use the sslPort.

fix(azure): use SSL port for redis in connection string

---

src/Digdir.Domain.Dialogporten.ChangeDataCapture/Dockerfile
src/Digdir.Domain.Dialogporten.Infrastructure/MigrationBundle.dockerfile
src/Digdir.Domain.Dialogporten.Service/Dockerfile
src/Digdir.Domain.Dialogporten.WebApi/Dockerfile

Ref this renovate PR: https://github.com/digdir/dialogporten/pull/543
To make it even more transparent as to what version we are using, we nail down the patch and sha instead of major and minor. 
We should probably use the `global.json` to specify the version in the Dockerfile eventually.

chore: update the dotnet runtime and SDK version in Dockerfiles

---

src/Digdir.Tool.Dialogporten.SlackNotifier/External/Slack/SlackClient.cs
src/Digdir.Tool.Dialogporten.SlackNotifier/Features/AzureAlertToSlackForwarder/ForwardAlertToSlack.cs

The Slack notifier function throws "invalid URI" once in a while, attempting to figure out what/why

chore: Temp debugging, log Slack Webhook URL

---

src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/DialogEntity.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Elements/DialogElement.cs
src/Digdir.Library.Entity.Abstractions/Features/Aggregate/AggregateNode.cs
src/Digdir.Library.Entity.EntityFrameworkCore/Features/Aggregate/AggregateExtensions.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Common/Events/DomainEventsTests.cs

* When deleting or updating a DialogElement, DialogUpdatedEvents where created.
* When deleting Element, NRE  was thrown. The parent dialog was not present (Element orphaned by EF Core), manually getting parent from aggregate tree

fix: UpdateDialogEvent created when dialog element is deleted or updated

---

docker-compose-no-webapi.yml

chore: Match Azure Redis version locally

---

.azure/modules/keyvault/copySecrets.bicep

Deployment names can not be longer than 64 characters. Trimming the secret name  + adding a unique hash to avoid potential conflicts.

fix(azure): avoid naming issue for secrets

---

docker-compose.yml
nginx.conf

In order to replicate the setup in Container Apps, we add a load balancer so we can have more than one replica of the web api.

chore: add load balancer for web api in docker-compose

---

src/Digdir.Domain.Dialogporten.Application/Common/Authorization/Constants.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogQuery.cs
tests/k6/tests/enduser/all-tests.js
tests/k6/tests/enduser/dialogDetails.js
tests/k6/tests/serviceowner/testdata/01-create-dialog.js

Also change "contains" to equality check when matching resources

fix: Require read action on elements without auth attr, replace unauthorized URLs

---

docs/swagger/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Content/DialogContentType.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240404082820_AddExtendedStatusContentType.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240404082820_AddExtendedStatusContentType.cs

feat: Add ExtendedStatus content type

---

src/Digdir.Domain.Dialogporten.GraphQL/ApplicationInsightEventListener.cs
src/Digdir.Domain.Dialogporten.GraphQL/Program.cs

Adding a custom DiagnosticEventListener for sending telemetry from GQL to ApplicationInsights
- #490

chore: Add custom DiagnosticEventListener for Application Insights

---

.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-staging.yml

- To ensure the tests are run regardless of if the previous jobs have been skipped, we add the same logic as for deploying apps. 
- Ensure tests are run only if backend code has been changes

ci: run k6 tests regardless if previous jobs skipped

---

src/Digdir.Domain.Dialogporten.Application/Common/IStringHasher.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Common/DialogApplication.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Dialogs/Queries/GetDialogTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Dialogs/Queries/SeenLogTests.cs

Adding tests for hash length on seen log, EndUser queries
Making sure we don't leak un-hashed user IDs
- #460

chore: Add EndUser SeenLog hash length tests

---

tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Queries/SeenLogTests.cs

Adding the same test as for EU, verifying user ID hashes length
- #460

chore(tests):  Add SeenLog tests for ServiceOwner

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Domain/Common/Constants.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/AuthorizedPartiesHelper.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/DecisionRequestHelper.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/ResourceRegistry/ResourceRegistryClient.cs

This fixes the handling of service resource values referring to Altinn apps so that they too use the same prefix as generic resources. The decision request helper now only checks for the reserved resource name prefix (`app_`) in order to determine how the XACML request should be constructed.
- #681

fix: Accept app references with urn:altinn:resource prefix

---

src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/AltinnAuthorizationClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Events/AltinnEventsClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/NameRegistry/NameRegistryClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/OrganizationRegistry/OrganizationRegistryClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/ResourceRegistry/ResourceRegistryClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Common/Exceptions/UpstreamServiceException.cs
src/Digdir.Domain.Dialogporten.Infrastructure/HttpClientExtensions.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Extensions/ErrorResponseBuilderExtensions.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Extensions/ExceptionHandlerExtensions.cs

This fixes #671 by implementing a wrapper via extension methods that causes post/get requests that don't return a successful message to throw exceptions.  
- #671

fix: Use HttpClient wrappers that ensure success to match FusionCache expectations

---

renovate.json

Renovate keeps trying to update dependencies in bicep files. Three different things seem to fail dependent on what is upgraded:
- The API version is not available in the region, which is the case for https://github.com/digdir/dialogporten/pull/706
- Types not available which is the case here https://github.com/digdir/dialogporten/actions/runs/9020616557/job/24786200707?pr=703
- Works, but not published in docs which is the case here: https://github.com/digdir/dialogporten/actions/runs/9048868949/job/24862382412?pr=720

chore: disable renovate for bicep files

---

docs/schema/V1/package.json
docs/schema/V1/schema.verified.graphql
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/DialogEntity.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/Common/ObjectTypes.cs

ExtendedStatus enum value missing for dialog content
- #732

fix(graphql): Add missing enum value ExtendedStatus in schema

---

src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureExtensions.cs
src/Digdir.Domain.Dialogporten.WebApi/Program.cs

~Seems like ResourceRegistry is already at 10s, try 20? 🤷🏼~
Setting debug log level for test environment
#655

chore: Set test environment log level for FusionCache

---

src/Digdir.Domain.Dialogporten.Application/Digdir.Domain.Dialogporten.Application.csproj

`AutoMapper.Extensions.Microsoft.DependencyInjection` is deprecated

chore: Update to AutoMapper 13

---

docs/schema/V1/package.json
docs/schema/V1/schema.verified.graphql
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/SearchDialogs/ObjectTypes.cs

If a GQL search hits a ValidationError, and the query contains OrderBy, the query fails with internal server error
(Attempting to return `null` on non-nullable value)

fix(graphql): Make OrderBy nullable

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Events/DomainEventToAltinnForwarderBase.cs

Missing a `/` in the source URL
- #747

fix: Fix broken source URL in cloud events

---

.azure/modules/serviceBus/main.bicep

When creating a private DNS zone, Azure creates a dynamic IP. However, we need to know this IP upfront in order to set the proper A-record
- #686

chore(azure): set static IP for private link in subnet

---

Directory.Build.props
src/Digdir.Domain.Dialogporten.Application/Digdir.Domain.Dialogporten.Application.csproj
src/Digdir.Domain.Dialogporten.ChangeDataCapture/Digdir.Domain.Dialogporten.ChangeDataCapture.csproj
src/Digdir.Domain.Dialogporten.ChangeDataCapture/Dockerfile
src/Digdir.Domain.Dialogporten.Domain/Digdir.Domain.Dialogporten.Domain.csproj
src/Digdir.Domain.Dialogporten.GraphQL/Digdir.Domain.Dialogporten.GraphQL.csproj
src/Digdir.Domain.Dialogporten.GraphQL/Dockerfile
src/Digdir.Domain.Dialogporten.Infrastructure/Digdir.Domain.Dialogporten.Infrastructure.csproj
src/Digdir.Domain.Dialogporten.Infrastructure/MigrationBundle.dockerfile
src/Digdir.Domain.Dialogporten.Service/Digdir.Domain.Dialogporten.Service.csproj
src/Digdir.Domain.Dialogporten.Service/Dockerfile
src/Digdir.Domain.Dialogporten.WebApi/Digdir.Domain.Dialogporten.WebApi.csproj
src/Digdir.Domain.Dialogporten.WebApi/Dockerfile
src/Digdir.Library.Entity.Abstractions/Digdir.Library.Entity.Abstractions.csproj
src/Digdir.Library.Entity.EntityFrameworkCore/Digdir.Library.Entity.EntityFrameworkCore.csproj
src/Digdir.Tool.Dialogporten.Benchmarks/Digdir.Tool.Dialogporten.Benchmarks.csproj
src/Digdir.Tool.Dialogporten.Ed25519KeyPairGenerator/Digdir.Tool.Dialogporten.Ed25519KeyPairGenerator.csproj
src/Digdir.Tool.Dialogporten.GenerateFakeData/Digdir.Tool.Dialogporten.GenerateFakeData.csproj
src/Digdir.Tool.Dialogporten.SlackNotifier/Digdir.Tool.Dialogporten.SlackNotifier.csproj
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Digdir.Domain.Dialogporten.Application.Integration.Tests.csproj
tests/Digdir.Domain.Dialogporten.Application.Unit.Tests/Digdir.Domain.Dialogporten.Application.Unit.Tests.csproj
tests/Digdir.Domain.Dialogporten.GraphQl.Integration.Tests/Digdir.Domain.Dialogporten.GraphQl.Integration.Tests.csproj
tests/Digdir.Domain.Dialogporten.Infrastructure.Unit.Tests/Digdir.Domain.Dialogporten.Infrastructure.Unit.Tests.csproj
tests/Digdir.Domain.Dialogporten.WebApi.Integration.Tests/Digdir.Domain.Dialogporten.WebApi.Integration.Tests.csproj

Moves the common build props to `Directory.Build.props` 
```
<TargetFramework>net8.0</TargetFramework>
<ImplicitUsings>enable</ImplicitUsings>
<Nullable>enable</Nullable>
<UserSecretsId>750256a4-f332-4783-8802-8a7d9566f9ca</UserSecretsId>
```
and uses this and .editorconfig inside docker images when building.
(More similar builds to what we do locally/in IDE)

chore(dotnet): Move common property group tags to Directory.Build.props

---

src/Digdir.Domain.Dialogporten.GraphQL/appsettings.Development.json
src/Digdir.Domain.Dialogporten.GraphQL/appsettings.staging.json
src/Digdir.Domain.Dialogporten.GraphQL/appsettings.test.json
src/Digdir.Domain.Dialogporten.WebApi/appsettings.Development.json
src/Digdir.Domain.Dialogporten.WebApi/appsettings.staging.json
src/Digdir.Domain.Dialogporten.WebApi/appsettings.test.json

Removed references to https://[ver2.maskinporten.no/.well-known/oauth-authorization-server/](https://ver2.maskinporten.no/.well-known/oauth-authorization-server/), as it seems to cause issues.

fix: remove maskinporten aux from config

---

.azure/infrastructure/main.bicep
.azure/modules/privateDnsZoneGroup/main.bicep
.azure/modules/redis/main.bicep

The default property seems to be publicNetworkAccess: 'Disabled', not possible to both configure private link and disable public network access at the same time it seems. Encountered this issue: https://github.com/Azure/azure-cli/issues/20997
Also, seems like we need to actually create the private DNS Zone manually, although the documentation states otherwise. Other sources say that if we use Bicep for this, we need to create it manually :)
Ran the Bicep manually from local machine, seems to update just fine. 

chore(azure): fix property conflict for redis

---

src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240610130651_AddPromptAndHttpMethodToGuiAction.cs

The migration fails when attempting to set HTTP verb defaults on the new GUI action property.
Default was set to 0, which violates ID restriction on the HTTP verb table. Default should be GET, same as in the create dialog command.

chore: Set HTTP verb default to GET in migration

---

src/Digdir.Domain.Dialogporten.WebApi/Common/Authentication/JwtSchemeSelectorMiddleware.cs

Some malformed tokens results in 500 errors in `JwtSchemeSelectorMiddleware`
- #868

fix(auth): Malformed JWTs no longer results in InternalServerError 

---

src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240620170240_ChangeDialogElementToDialogAttachment.cs

Did not properly check that the migration worked *with data in the database* 🤦🏼 
Instead of 
```csharp
migrationBuilder.RenameColumn(
name: "ElementId",
table: "LocalizationSet",
newName: "AttachmentId");
migrationBuilder.RenameIndex(
name: "IX_LocalizationSet_ElementId",
table: "LocalizationSet",
newName: "IX_LocalizationSet_AttachmentId");
```
we need to drop the column, or else we get an FK error on the old ElementIds against the new attachment table.
```csharp
migrationBuilder.DropIndex(
name: "IX_LocalizationSet_ElementId",
table: "LocalizationSet");
migrationBuilder.DropColumn(
name: "ElementId",
table: "LocalizationSet");
migrationBuilder.AddColumn<Guid>(
name: "AttachmentId",
table: "LocalizationSet",
type: "uuid",
nullable: true);
migrationBuilder.CreateIndex(
name: …
```

chore: Fix migration for DialogElements renaming to Attachments

---

README.md

This gives proper error details when postgresql explodes locally. 
Change your local version manually, if needed
`~/.microsoft/usersecrets/750256a4-f332-4783-8802-8a7d9566f9ca/secrets.json` 
Add `Include Error Detail=True;` to `Infrastructure:DialogDbConnectionString`

chore: Include error details in local user secret connection string

---

.github/workflows/action-run-k6-tests.yml

This should case the pipeline to fail if there's errors in the tests, as per https://github.com/EnricoMi/publish-unit-test-result-action
- #876

chore(ci/cd): Fail pipeline if there's k6-test errors

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogDto.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Content/DialogContentType.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240703094112_AddDefaultMediaTypeForPlainTextContent.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240703094112_AddDefaultMediaTypeForPlainTextContent.cs

To be more explicit with media typing, we add 'text/plain' to the content types `Title`, `SenderName`, `Summary`, and `ExtendedStatus`.
This also simplifies error messaging in the create and update validators
- #889

chore: Add default media type for plain text content types

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/SearchDialogQueryValidator.cs

* Adds missing property name to problem details
* Adds missing separator in urn
```json
"errors": {
"": [
"'EndUserId' must be a valid end user identifier. It should match the format 'urn:altinn:person:identifier-no{norwegian f-nr/d-nr}' or 'urn:altinn:systemuser{uuid}'."
],
```
```json
"errors": {
"EndUserId": [
"End User Id must be a valid end user identifier. It must match the format 'urn:altinn:person:identifier-no:{norwegian f-nr/d-nr}' or 'urn:altinn:systemuser:{uuid}'."
],
```

chore: Fix validation error message for EndUserId on search

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommandValidator.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Common/DialogApplication.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/UpdateDialogTests.cs

It is currently not possible to create a new DialogActivity that refers to an old DialogActivity via `relatedActivityId`
This check in the validator requires the referred Id to be present in the DTO, which we don't allow. 
```cshap
RuleForEach(x => x.Activities)
.IsIn(x => x.Activities,
dependentKeySelector: activity => activity.RelatedActivityId,
principalKeySelector: activity => activity.Id)
.SetValidator(activityValidator);
```
This suggestion is to move this check from the validator to the handler and load all activities to verify the relation ID.
- #931

fix: Allow new activities to reference old activities

---

.azure/bicepconfig.json
.azure/functions/resourceName.bicep
.azure/modules/appConfiguration/create.bicep
.azure/modules/functionApp/slackNotifier.bicep
.azure/modules/postgreSql/create.bicep
.azure/modules/redis/main.bicep
.azure/modules/serviceBus/main.bicep

Meeting some issues when creating resources in another subscription. Some resource names are global across the azure infrastructure. Another potential issue is DoS if someone uses our prefix to create resources.
- Add two helper functions to help generate unique resource names
- Adds a unique postfix based on resourcegroup id and subscription id on the resources that requires globally unique names. 
- Slack notifier storage account is a bit different as it has max 24 chars and needs lowercase letters and numbers only. Refactored to work fine, but we should look into creating a common storage account
- #783

chore(azure): add unique resource names

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Purge/PurgeDialogCommand.cs

Query filter makes it impossible to purge a softly deleted dialog
- #939

fix(WebAPI): Allow purging of softly deleted dialogs

---

.github/workflows/action-publish-schema.yml

- Publishing the same version will fail. If we for example retry the workflow for staging which will use the same tag

ci: prevent schema from trying to publish existing version

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs

Introduced a bug when implementing Transmissions, changed the existing activities check to only check on the dialog. 
Reverted to check the entire table.
Also added the same check that was missing for Transmission IDs
- #959

fix: Using existing transmission/activity IDs should return HTTP 422

---

src/Digdir.Domain.Dialogporten.WebApi/Common/Authentication/TokenIssuerCache.cs
src/Digdir.Domain.Dialogporten.WebApi/Program.cs

Noticed this when attempting to debug on the airplane going back home.
It is not possible to query the api when offline, with auth disabled 
TokenIssuerCache calls times out, results in HTTP500
This disables the TokenIssuerCache when DisableAuth is set
Manually tested on plane ✈️

chore: Disbale token issuer cache when auth is disabled

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs

fix: Using existing Transmission or Activity IDs should no longer result in internal server error on updates

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs

Not adding as "fix", there is already a note on a previous fix that is related in the release notes
Related issue: #981

chore: Add existing ID checks for transmission attachments

---

docs/schema/V1/schema.verified.graphql
docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Externals/AltinnAuthorization/AuthorizedPartiesResult.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Parties/Queries/Get/GetPartiesDto.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/Parties/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/AltinnAuthorizationClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/AuthorizedPartiesHelper.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/LocalDevelopmentAltinnAuthorization.cs

This adds a flag to the parties dto that is set to true if the given party matches the authenticated user as per discussed last refinement.
- N/A

feat: Add current user flag to parties dto

---

README.md

This is the guide to set up a new environment as it currently stands. We can most likely cut out some of the points and reduce the amount of github secrets with further work on the CI/CD
- #845

docs(infra): add deploying a new environment

---

.github/workflows/ci-cd-prod.yml

Will run a dry-run of the deployment to both infra and apps on a new release. Will have to be reviewed manually before deployment happens. 
We now have a full workflow for deployment to production. Some time in the not so very near future, I think it would be wise to split up the dry-run part and the deployment itself. As right now it would require a review from any of us to even start the dry-run, which should happen automatically on every release. 
- #845

ci: add production workflow

---

.github/workflows/dispatch-apps.yml
.github/workflows/dispatch-infrastructure.yml

Adding environment as a part of the concurrency group in order to be able to deploy to several environments at the same time when dispatching infra or apps manually

ci: add env as part of concurrency

---

src/Digdir.Domain.Dialogporten.Infrastructure/Digdir.Domain.Dialogporten.Infrastructure.csproj

Reverts digdir/dialogporten#1034
Endpoints are throwing 401 errors with the new client, reverting change for now

Revert "chore: Update Maskinporten API client "

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Common/Extensions/ClaimsPrincipalExtensions.cs
src/Digdir.Domain.Dialogporten.Application/Externals/AltinnAuthorization/DialogDetailsAuthorizationResult.cs
src/Digdir.Domain.Dialogporten.Application/Externals/AltinnAuthorization/IAltinnAuthorization.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogActivities/Queries/Search/SearchDialogActivityQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogSeenLogs/Queries/Get/GetDialogSeenLogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogSeenLogs/Queries/Search/SearchDialogSeenLogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogTransmissions/Queries/Get/GetDialogTransmissionQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogTransmissions/Queries/Search/SearchDialogTransmissionQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/GetDialogQueryValidator.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/DialogEntity.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/AltinnAuthorizationClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/LocalDevelopmentAltinnAuthorization.cs
src/Digdir.Domain.Dialogporten.Infrastructure/UnitOfWork.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Authentication/ServiceOwnerOnBehalfOfPersonMiddleware.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogActivities/Create/CreateDialogActivityEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogTransmissions/Create/CreateDialogTransmissionEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Get/GetDialogEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Patch/PatchDialogsController.cs
src/Digdir.Domain.Dialogporten.WebApi/Program.cs

Add optional EndUserId param to ServiceOwner Get Dialog details API
- #386

feat: Add optional EndUserId param to ServiceOwner Get Dialog details API

---

src/Digdir.Domain.Dialogporten.Application/Common/IDialogTokenGenerator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogQuery.cs

This fixes the `iss` claim getting either two slashes or no slashes after the base uri part, due some `Uri` ToString() behaviour I do not fully understand. 
Before this fix, tokens made on test (any other environment than localdev) missed a slash resulting in `iss` claim being `https://altinn-dev-api.azure-api.net/dialogportenapi/v1`. This was due to the call to `GetDialogToken` missing a leading slash. However, this resulted in double slashes when running locally, ie `https://localhost:7247//api/v1`. Both configurations are defined with `BaseUri` values without trailing slashes.
The fix consists of adding a leading slash to the `GetDialogToken` call, and trimming any trailing slash from the `BaseUri` when concatenating in `DialogGenerator`
- N/A

fix: Fix iss claim in dialog token

---

src/Digdir.Domain.Dialogporten.Application/Common/Authorization/Constants.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Content/ContentValueDtoValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Contents/DialogContentType.cs
src/Digdir.Domain.Dialogporten.Domain/MediaTypes.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240903130302_RemoveHtmlSupportFromDialogContent.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20240903130302_RemoveHtmlSupportFromDialogContent.cs

This "hides" HTML support from the API, only allowed with legacy scope.
Scope is to be used when importing old stuff from Altinn2/3 to Dialogporten
- #894

feat(webapi): Require legacy scope for HTML support

---

src/Digdir.Domain.Dialogporten.Application/Common/Extensions/Enumerables/AsyncEnumerableExtensions.cs
src/Digdir.Domain.Dialogporten.Application/Externals/IDialogDbContext.cs
src/Digdir.Domain.Dialogporten.Application/Externals/IResourceRegistry.cs
src/Digdir.Domain.Dialogporten.Application/Externals/ISubjectResourceRepository.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ResourceRegistry/Commands/Synchronize/SynchronizeSubjectResourceMappingsCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ResourceRegistry/Commands/Synchronize/SynchronizeSubjectResourceMappingsCommandValidator.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/ResourceRegistry/LocalDevelopmentResourceRegistry.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/ResourceRegistry/ResourceRegistryClient.cs
src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureExtensions.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Repositories/SubjectResourceRepository.cs
src/Digdir.Domain.Dialogporten.Janitor/Commands.cs
src/Digdir.Domain.Dialogporten.Janitor/Properties/launchSettings.json
src/Digdir.Library.Entity.Abstractions/Features/Identifiable/IdentifiableExtensions.cs

Hvis dette godkjennes, fungerer det slik:
1. Hent sist oppdatert dato fra enten kommando input, eller den største UpdatedAt i SubjectResources tabellen, eller DateTimeOffset.MinValue (i den rekkefølgen).
2. Stream subjekt-ressurs-mappings batchvis fra ressursregisteret
3. Stapp det inn i DB via en merge statement
4. Repiter steg 2 og 3 til ressursregisteret ikke har noen flere mappings
MERK - nå brukes ikke SubjectResourceLastUpdates tabellen ettersom siste oppdateringsdato hentes fra SubjectResources. Jeg tror dette blir korrekt. I tillegg gjør dette at vi ikke trenger å ta hensyn til server clock drift ettersom SubjectResources.UpdatedAt hentes og populeres direkte fra ressurs registeret. Altså vi bruker ikke DP sin tid, vi bruker ressurs registeret sin tid. Eneste er at når vi er …

Some suggestions to Bjørn

---

.azure/applications/sync-subject-resource-mappings-job/main.bicep
.azure/applications/sync-subject-resource-mappings-job/prod.bicepparam
.azure/applications/sync-subject-resource-mappings-job/staging.bicepparam
.azure/applications/sync-subject-resource-mappings-job/test.bicepparam
.azure/modules/containerAppJob/main.bicep
.github/workflows/action-deploy-apps.yml

Apparently, the `command` property in Bicep for Azure Container Apps overrides the `ENTRYPOINT` property in the `Dockerfile` 🤷  Changing to using arguments instead. Tested with manual update of the container app job. 
https://azureossd.github.io/2024/01/17/Container-Apps-Using-the-command-override-option/
Other things:
- Added application insights connection string
- Added `ASPNETCORE_ENVIRONMENT` in order to use correct appconfig-file

fix: ensure jobs are run with correct arguments and parameters

---

.azure/applications/sync-subject-resource-mappings-job/main.bicep
docker-compose-jobs.yml
src/Digdir.Domain.Dialogporten.Janitor/Program.cs

fix: ensure correct appsettings is used

---

.gitignore
README.md
src/Digdir.Domain.Dialogporten.Application/Common/Extensions/ConfigurationExtensions.cs
src/Digdir.Domain.Dialogporten.GraphQL/Program.cs
src/Digdir.Domain.Dialogporten.Janitor/Program.cs
src/Digdir.Domain.Dialogporten.Service/Program.cs
src/Digdir.Domain.Dialogporten.WebApi/Program.cs

Det blir naturlig nok litt flikking av config under lokal utvikling. Noe av denne konfigurasjonen er _ment_ for å deles gjennom git. Eksempelvis endepunktet til en ny integrasjon i test. Annen konfigurasjon er kun ment uneder en spesifikk debugg sesjon eller som den spesifikke utviklers preferanser, som _ikke burde deles_ gjennom git. Eksempelvis det å åpne opp for lavere logg nivå enn warning. 
I denne PRen legger jeg på rammer for å kunne introdusere en appsettings.local.json fil. Konfigurasjonen her har prioritet over *all* annen config og den lastes kun inn i Development environment. I tillegg blir den ignorert av git gjennom .gitignore fila. 
Dersom uviklere nå skal legge på konfigurasjon som er greit å dele så brukes appsettings.Development.json. Dersom det er konfigurasjon som ikke …

chore: Add local appsettings support

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs
src/Digdir.Tool.Dialogporten.GenerateFakeData/DialogGenerator.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/UpdateDialogTests.cs

Regression(?), or missed bug from when transmissions where introduced.
* Added missing return when finding existing IDs
* Adjusted the log message for existing activities to use the same extension method as transmissions
* Added tests for both existing activities and existing transmissions 
- #1088

fix(webapi): Return 422 when existing transmission IDs are used in dialog update

---

tests/k6/common/dialog.js
tests/k6/tests/enduser/dialogSearch.js
tests/k6/tests/serviceowner/dialogSearch.js

Fixed k6 tests to work with new dialog status
[#1084](https://github.com/digdir/dialogporten/issues/1084)

chore: Updated k6 to use new dialog status

---

src/Digdir.Domain.Dialogporten.Application/ApplicationExtensions.cs

I think it reads better without the space (?) 🤔
It also matches when we use nameOf()
Old: 
New:

chore: Remove space from property names in validation errors

---

Digdir.Domain.Dialogporten.sln
tests/Digdir.Domain.Dialogporten.Architecture.Tests/DialogportenAssemblies.cs
tests/Digdir.Domain.Dialogporten.Architecture.Tests/Digdir.Domain.Dialogporten.Architecture.Tests.csproj
tests/Digdir.Domain.Dialogporten.Architecture.Tests/Medo/MedoUsageTests.cs

This adds a new architecture test project which uses [NetArchTest](https://github.com/BenMorris/NetArchTest) to check all assemblies for usage of the `Medo` library.
It should only be used in `IdentifiableExtensions`, so that we can control/guarantee that we are using it correctly when it comes to endianness.
- #1071

chore(test): Add architecture test for Medu.Uuidv7 usage

---

.azure/modules/functionApp/slackNotifier.bicep

A more generalized query to filter out more noise from APIM (while we try to fix the root cause)

chore: generalized query for slack notifier

---

src/Digdir.Domain.Dialogporten.GraphQL/appsettings.Development.json
src/Digdir.Domain.Dialogporten.GraphQL/appsettings.prod.json
src/Digdir.Domain.Dialogporten.GraphQL/appsettings.staging.json
src/Digdir.Domain.Dialogporten.GraphQL/appsettings.test.json
src/Digdir.Domain.Dialogporten.GraphQL/appsettings.yt01.json

fix(graphql): ensure gql has maskinporten environment set

---

.github/workflows/workflow-send-ci-cd-status-slack-message.yml

Missing required parameter after update to v2

chore(ci): Add missing method parameter when sending Slack message

---

.gitignore
src/Digdir.Domain.Dialogporten.Application/Common/Authorization/Constants.cs
src/Digdir.Domain.Dialogporten.Application/Common/Authorization/IServiceResourceAuthorizer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/ResourceRegistry/ResourceRegistryClient.cs

From support: 
1. User found resource `digdir-maskinportenschemaid-8` in RR
2. User tried to create a dialog on resource `urn:altinn:resource:digdir-maskinportenschemaid-8`
3. Got message `Service resource 'urn:altinn:resource:digdir-maskinportenschemaid-8' does not exist in the resource registry`
Dialogporten only supports the following resource types:
- GenericAccessResource
- AltinnApp
- CorrespondenceService
This PR will improve the previous message to the following: `Service resource 'urn:altinn:resource:digdir-maskinportenschemaid-8' does not exist in the resource registry, or is not of the following supported resource types: [GenericAccessResource, AltinnApp, CorrespondenceService].`

chore: Improve error message when unable to find resource in resource registry.

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.WebApi/OpenApiDocumentExtensions.cs
src/Digdir.Domain.Dialogporten.WebApi/Program.cs

chore(webapi): Fix JWTBearerAuth scheme name casing

---

.env

`dialogporten != Dialogporten` 
Had some confusing moments in pgAdmin with dual databases 😇

chore: Use correct database name for local Docker setup

---

.github/slack-templates/pipeline-failed.json
.github/workflows/ci-cd-yt01.yml
.github/workflows/workflow-send-ci-cd-status-slack-message.yml

ci: send slack message on failed performance tests

---

.azure/infrastructure/staging.bicepparam

Related to https://digdir.slack.com/archives/C079D6PAGDS/p1734018202302459
Experiencing heavy CPU usage on the postgresql server in staging. After some investigations,  it was hard to pin down the cause. Being on a burstable tier may be too fragile, and perhaps contribute to the high CPU usage, so upgrading. Staging will be used by many test environments moving forward so making it more stable with GeneralPurpose machines makes sense. 
- #N/A

fix(azure): adjust SKU and storage for staging

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Content/ContentValueDto.cs

chore(webapi): Remove specific mediatypes on ContentValueDto

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommandValidator.cs
tests/Digdir.Domain.Dialogporten.Application.Unit.Tests/Features/V1/ServiceOwner/Activities/ActivityValidatorTests.cs

The validator activity validator allows setting TransmissionId on every activity type except DialogOpened.
It should only allow on TransmissionOpened.
- #1630

fix(webapi): Only allow transmissionId on TransmissionOpened activities

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Events/CloudEventTypes.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Activities/DialogActivityType.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20241222195253_AddAdditionalActivityTypes.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20241222195253_AddAdditionalActivityTypes.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/Common/Events/DomainEventsTests.cs

feat: Add additional types to DialogActivity

---

src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/AltinnAuthorizationClient.cs

Add dedicated scope and dbcontext to GetSubjectResources to avoid concurrency errors
- #1649

fix(app): Add dedicated scope and dbcontext to GetSubjectResources

---

src/Digdir.Domain.Dialogporten.GraphQL/ServiceCollectionExtensions.cs

Missing some depth to allow the inspection query through 
Issue #1680

fix(graphql): Set max execution depth to allow inspection query

---

src/Digdir.Domain.Dialogporten.WebApi/Program.cs

The mapping of health-check endpoints was removed. Re-enabling again now. 

fix(web-api): re-enable health checks

---

.github/workflows/ci-cd-yt01.yml
tests/k6/scripts/generate_all_tests.ps1
tests/k6/scripts/generate_all_tests.sh
tests/k6/tests/enduser/all-tests.js
tests/k6/tests/enduser/performance/enduserSearchWithThresholds.js
tests/k6/tests/performancetest_data/endusers-localdev.csv
tests/k6/tests/performancetest_data/serviceowners-localdev.csv
tests/k6/tests/serviceowner/all-tests.js
tests/k6/tests/serviceowner/performance/createDialogWithThresholds.js
tests/k6/tests/serviceowner/performance/serviceOwnerSearchWithThresholds.js

Removed the threshold tests which are used only in performance tests, and moved the files under `/performance`. Also removed some unneded data files that were only required for testing towards at21
- N/A

test: exclude threshold tests from all tests

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogQuery.cs

Removed .AsSingleQuery from EndUser Search query.
Tested locally with 50 million dialogs. Results show that the removal of .AsSingleQuery() brings Enduser Search query performance up to par with that of ServiceOwner Search. We should seek further improvements as well, as query scaling seems to be an issue.
- #1706

fix: Removed .AsSingleQuery from EndUser Search query

---

src/Digdir.Domain.Dialogporten.WebApi/Common/Authorization/AuthorizationPolicy.cs

fix: Use correct type filter for LocalDevelopmentUser

---

.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-release-please.yml
.github/workflows/ci-cd-staging.yml
.github/workflows/ci-cd-yt01.yml
.github/workflows/workflow-send-ci-cd-status-slack-message.yml

This change streamlines our Docker image management by building and publishing images only once when a release is created, rather than rebuilding for each environment. These published images are then reused across staging, yt01 and production deployments.
1. Get the previous release SHA before creating a new release
2. Only trigger Docker image builds when there are backend changes since the previous release
3. Trigger staging/yt01 deployment via repository dispatch after successful release
Next up:
- Trigger a dry-run of deployment to production
- Notify dry-run of production is complete in Slack
- Add deploy-to-production workflow without dry-run and environment gating
- #1692

ci: ensure image is published once

---

.github/workflows/ci-cd-release-please.yml
.github/workflows/ci-cd-staging.yml
.github/workflows/ci-cd-yt01.yml

include the version number in the workflow run name for yt01 and staging. It looks weird that every workflow run should be named the event-name aka "release_created"
- #1692

ci: ensure that workflow run name of staging and yt01 contains the version number

---

src/Digdir.Domain.Dialogporten.Domain/Common/DomainEvents/DomainEvent.cs
src/Digdir.Domain.Dialogporten.Domain/Common/EventPublisher/IDomainEvent.cs

Previous release pushed to all environments, all outbox messages tables checked

chore: Remove old OccuredAt property on DomainEvent

---

src/Digdir.Domain.Dialogporten.GraphQL/Common/Authorization/AuthorizationOptionsSetup.cs
src/Digdir.Domain.Dialogporten.GraphQL/Common/Authorization/AuthorizationPolicy.cs
src/Digdir.Domain.Dialogporten.GraphQL/Common/Authorization/AuthorizationPolicyBuilderExtensions.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Authorization/AuthorizationOptionsSetup.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Authorization/AuthorizationPolicy.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Authorization/AuthorizationPolicyBuilderExtensions.cs

fix(auth): Allow .noconsent scope in EndUser auth policy

---

.github/workflows/ci-cd-prod-dry-run.yml
.github/workflows/ci-cd-prod.yml
.github/workflows/workflow-deploy-apps.yml
.github/workflows/workflow-get-current-version.yml

A step towards easier deployment to production. 
- Separated dry-run and actual deployment into two workflows. 
- The dry-run will run at the same time deployment to staging/yt01 takes place
- Actual deploy has to be run manually for now. 
- Environment gating will be removed from production to allow for more seamless production deploy
Other improvements later: 
- Notify on Slack when a dry-run has completed for production deployment with a button to trigger the workflow for deployment
- #1692

ci: separate between dry-run and real production deploy

---

.github/workflows/ci-cd-prod.yml
.github/workflows/ci-cd-staging.yml
.github/workflows/ci-cd-yt01.yml
.github/workflows/workflow-deploy-apps.yml

All environments still seem to store the version number only if the jobs are not skipped. Refactoring to removing "Cancelled" checking for if jobs are skipped to ensure that we store the version if the apps are deployed. 
- #1692

ci: ensure version is stored on app deploy

---

src/Digdir.Domain.Dialogporten.GraphQL/Common/Authorization/AuthorizationOptionsSetup.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Authorization/AuthorizationOptionsSetup.cs

fix(auth): Split values when checking EndUser scopes

---

docs/schema/V1/schema.verified.graphql
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/Common/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/DialogById/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/MutationTypes/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/SearchDialogs/MappingProfile.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/SearchDialogs/ObjectTypes.cs

fix(graphql): Add SystemLabel search filter

---

src/Digdir.Domain.Dialogporten.GraphQL/Digdir.Domain.Dialogporten.GraphQL.csproj
src/Digdir.Domain.Dialogporten.Janitor/Digdir.Domain.Dialogporten.Janitor.csproj
src/Digdir.Domain.Dialogporten.Service/Digdir.Domain.Dialogporten.Service.csproj
src/Digdir.Domain.Dialogporten.WebApi/Digdir.Domain.Dialogporten.WebApi.csproj

After some debugging, we found out that the only thing different that is related to opentelemetry are updates of these dependencies. 
1.47.1 seemed to work, but not 1.47.2. https://github.com/Altinn/dialogporten/compare/88a9217846afaa1580f9430c52e2f880bd4906c1...d9281fc697b6ad613c5546b1cd81a115e349bde4
(this is a bit fragile, so we need to consider other options, or adding alerts that notify us if we don't get any traces anymore)
Reverted commit: 75c7a24f3897eb6a64dc63463d3db492f44ebd79.

fix(deps): ensure traces are sent to application insights

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/GetDialogQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/SearchDialogQuery.cs

GetCurrentUserInformation performs a name lookup which isn't used in search, causing a needless lookup to Registry (and Altinn 2) for searches. Also, moves the current user name lookup in Get to be performed after all early returns to avoid doing it needlessly. 
- N/A

chore: Remove unneeded name lookup

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/SearchDialogQuery.cs

`?deleted` and `?deleted=` query params on ServiceOwner search is not handled as default (exclude)
- #1825

fix(webapi): Correctly handle deleted filter null value on ServiceOwner search

---

src/Digdir.Domain.Dialogporten.Application/Common/Authorization/Constants.cs
src/Digdir.Domain.Dialogporten.Application/Common/Extensions/ClaimsPrincipalExtensions.cs
src/Digdir.Domain.Dialogporten.Application/Common/IUserResourceRegistry.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/Common/Content/ContentValueDtoValidator.cs
src/Digdir.Domain.Dialogporten.GraphQL/Common/Authentication/LocalDevelopmentUser.cs
src/Digdir.Domain.Dialogporten.GraphQL/Common/Authorization/AuthorizationOptionsSetup.cs
src/Digdir.Domain.Dialogporten.GraphQL/Common/Authorization/AuthorizationPolicy.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Authentication/ServiceOwnerOnBehalfOfPersonMiddleware.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Authorization/AuthorizationOptionsSetup.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Authorization/AuthorizationPolicy.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/LocalDevelopmentUser.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogTransmissions/Get/GetDialogTransmissionEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogTransmissions/Search/SearchDialogTransmissionEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogActivities/Create/CreateDialogActivityEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogActivities/Get/GetDialogActivitySwaggerConfig.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogActivities/NotificationCondition/SearchDialogActivityEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogActivities/Search/SearchDialogActivityEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogTransmissions/Create/CreateDialogTransmissionEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogTransmissions/Get/GetDialogTransmissionEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogTransmissions/Search/SearchDialogTransmissionEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Create/CreateDialogEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Delete/DeleteDialogEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Get/GetDialogEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Purge/PurgeDialogEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Search/ListDialogEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Update/UpdateDialogEndpointSummary.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Commands/CreateDialogTests.cs

Forsøker meg i første omgang på å samle alle scopene vi bruker i dialogporten slik at det er lett å få en oversikt over dem. @knuhau og jeg forsøkte oss også på å komme med noen summaries for hvert scope. Her tar vi veldig gjerne imot innspill på en bedre forklarende tekst @oskogstad @elsand 🙏 
Related issue #647

chore: Consolidate all scopes to one location with xml doc.

---

tests/k6/tests/serviceowner/performance/createDialogWithThresholds.js
tests/k6/tests/serviceowner/performance/createTransmissionsWithThresholds.js

Tweaked thresholds for create dialogs and transmissions
- #1862

chore(performance): tweaked thresholds

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogTransmissions/Queries/Get/GetTransmissionQuery.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogTransmissions/Queries/Search/SearchTransmissionQuery.cs

EndUser transmission endpoints gives out original URLs when the user is not authorized to see them
- #1889

fix(webapi): Mask unauthorized attachment URLs in EndUser transmission endpoints

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.WebApi/Common/Swagger/TypeNameConverter.cs

Updated TypeNameConverter to not remove half words from Prefixes (Delete from Delted, Patch from Patched)

chore: updated TypeNameConverter

---

src/Digdir.Domain.Dialogporten.Application/Common/Authorization/Constants.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogActivities/Create/CreateDialogActivityEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogTransmissions/Create/CreateDialogTransmissionEndpoint.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Patch/PatchDialogsController.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/Dialogs/Update/UpdateDialogEndpoint.cs

feat(webapi): Add flag for disabling SystemLabel reset

---

.github/ISSUE_TEMPLATE/new-change-in-functionality.md

https://github.blog/changelog/2025-02-18-github-issues-projects-february-18th-update/#tasklist-blocks-will-be-retired-and-replaced-with-sub-issues

trivial: Remove tasklist syntax from issue templates

---

.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-prod.yml
.github/workflows/ci-cd-staging.yml
.github/workflows/workflow-check-for-changes.yml

WebApiClient NuGet is now also pushed on changes in the WebApiClient not only on schema changes

chore: updated push sdk to NuGet workflow on WebApiClient changes

---

.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-staging.yml

Co-authored-by: Magnus Sandgren <5285192+MagnusSandgren@users.noreply.github.com>
Co-authored-by: Are Almaas <arealmaas@gmail.com>
Co-authored-by: Amund Myrbostad <Lullinj98@gmail.com>

ci: Use alpha suffix for NuGet pre-release in test environment

---

.azure/modules/postgreSql/create.bicep

No longer needed as we went for a different pattern than CDC for events. 
- #164

trivial: remove comments about wal

---

src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Configurations/Dialogs/DialogEntityConfiguration.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Configurations/Dialogs/DialogSearchTagConfiguration.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Configurations/Localizations/LocalizationConfiguration.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Constants.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/DialogDbContext.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/IdempotentNotifications/NotificationAcknowledgement.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Interceptors/ConvertDomainEventsToOutboxMessagesInterceptor.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20250226145405_CreateGinIndexOnLocalizationsAndSearchTags.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20250226145405_CreateGinIndexOnLocalizationsAndSearchTags.cs

- #[1650](https://github.com/Altinn/dialogporten/issues/1650)
Co-authored-by: Bjørn Dybvik Langfors <bdl@digdir.no>
Co-authored-by: Magnus Sandgren <5285192+MagnusSandgren@users.noreply.github.com>

feat: Add reverse indexes on Localizations and SearchTags

---

docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Common/Actors/ActorDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Common/Actors/ActorDto.cs
src/Digdir.Library.Dialogporten.WebApiClient/Features/V1/RefitterInterface.cs

The summaries used on the common ActorDto was referring to transmissions, and including information only relevant for serviceowner POST. Reworded/simplified so that the summaries make sense in any context.

chore: Fix actor DTO summaries

---

src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Configurations/Dialogs/DialogEntityConfiguration.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20250305165700_AddMissingSearchIndexesExtStatusExtRefDeleted.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20250305165700_AddMissingSearchIndexesExtStatusExtRefDeleted.cs
src/Digdir.Library.Entity.EntityFrameworkCore/Features/SoftDeletable/SoftDeletableExtensions.cs

Adding indexes for dialog
* Deleted
* ExtendedStatus
* ExtendedReference
* VisibleFrom
- #2001

fix(db): Add missing indexes for search

---

docs/schema/V1/schema.verified.graphql
docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Get/DialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogDto.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Get/DialogDto.cs
src/Digdir.Domain.Dialogporten.Domain/Dialogs/Entities/Actions/DialogApiAction.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/DialogById/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20250311092108_AddApiActionName.Designer.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/Migrations/20250311092108_AddApiActionName.cs
src/Digdir.Library.Dialogporten.WebApiClient/Features/V1/RefitterInterface.cs
src/Digdir.Tool.Dialogporten.GenerateFakeData/DialogGenerator.cs
tests/k6/tests/serviceowner/testdata/01-create-dialog.js

Added an optional name field to ApiActions, to allow for easier identification of the purpose of the action.
- #2032

feat: Add Name to ApiAction as optional field

---

src/Digdir.Domain.Dialogporten.GraphQL/appsettings.Development.json
src/Digdir.Domain.Dialogporten.GraphQL/appsettings.test.json
src/Digdir.Domain.Dialogporten.Janitor/appsettings.Development.json
src/Digdir.Domain.Dialogporten.Janitor/appsettings.test.json
src/Digdir.Domain.Dialogporten.Service/appsettings.Development.json
src/Digdir.Domain.Dialogporten.Service/appsettings.test.json
src/Digdir.Domain.Dialogporten.WebApi/appsettings.Development.json
src/Digdir.Domain.Dialogporten.WebApi/appsettings.test.json

Dependent on the resources being created in resource registry for `at23`
- #1966
TODO before merge: Update subscription id for test environment in key vault

fix(apps): ensure we use at23 as backend instead of tt02 in test env

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/CreateDialogCommand.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Update/UpdateDialogCommand.cs

Pending final decision on how transmission hierarchy should be restricted, we need to increase max width to unblock Skatt. At the same time, the max depth has been reduced to 20. As the transmission feature is not widely used, future restrictions is deemed to be manageable to roll out without too much breakage.

feat: Loosen transmission hierarchy restrictions

---

.azure/modules/ssh-jumper/main.bicep
.azure/modules/virtualMachine/main.bicep

Enables just-in-time for the ssh-jumpers. In order to use the database-forwarder, you need to enable JIT in the portal. I will add this as a script in the database-forwarder ASAP so it will happen automatically so we don't need to go to the portal each time. 
Tips for later:
- Add Office IP only for production
- Increase the max duration for all other envs than production (1HR is a bit low)
- #1995

feat(infra): enable JIT for ssh-jumper

---

.azure/infrastructure/main.bicep
.azure/modules/vnet/main.bicep

- We will enable [JIT for all ssh-jumpers](https://github.com/Altinn/dialogporten/pull/2091). This will automatically add a `Deny` on port `22`. [When utilizing the script to open use JIT](https://github.com/Altinn/dialogporten/pull/2102), it will automatically add a rule to allow source IP on port `22`
- Refactor a bit by putting constants for addressprefixes on top
- Later we will restrict outbound traffic as well: https://github.com/Altinn/dialogporten/pull/2098
- #1995

fix(infra): restrict inbound network for ssh jumper

---

.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-prod.yml
.github/workflows/ci-cd-staging.yml
.github/workflows/ci-cd-yt01.yml
.github/workflows/workflow-swarmia-deployment.yml

Swarmia by default uses the deployment from github. We trigger a deployment way too often because a deployment is registered whenever we use a workflow related to an environment. This leads to multiple registered deployments per deployment. 
- #N/A

ci: send deployment information to swarmia

---

.azure/modules/applicationInsights/availabilityTest.bicep

The availability test is failing in `production`: https://digdir.slack.com/archives/C079XRW5G5A/p1744178965215129
The reason is that the SSL certificate expires in 7 days. The SSL certificate is handled in APIM. No need for us to handle this. 
- #N/A

fix(infra): remove ssl check in availability tests

---

src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureExtensions.cs

This is an attempt to reduce lock contention with MassTransit and outbox usage.
- N/A

fix: Reduce isolation level for outbox

---

.azure/applications/graphql/main.bicep
.azure/applications/graphql/prod.bicepparam
.azure/applications/graphql/yt01.bicepparam
.azure/applications/service/main.bicep
.azure/applications/web-api-eu/main.bicep
.azure/applications/web-api-eu/prod.bicepparam
.azure/applications/web-api-eu/yt01.bicepparam
.azure/applications/web-api-so/main.bicep
.azure/applications/web-api-so/prod.bicepparam
.azure/applications/web-api-so/yt01.bicepparam
.azure/infrastructure/main.bicep
.azure/infrastructure/prod.bicepparam
.azure/infrastructure/yt01.bicepparam
.azure/modules/containerApp/main.bicep
.azure/modules/containerAppEnv/main.bicep

Reverting because a network change is needed in order to change from consumption only to workload profiles. 
https://learn.microsoft.com/en-us/azure/container-apps/environment#types
- #2257

fix(infra): revert workload profiles for CAE

---

.azure/infrastructure/prod.bicepparam
.azure/infrastructure/yt01.bicepparam

A minimum of 3 instances are recommended due to redundancy. We also consume 2 instances by just running on current replicas. 
- #2257

chore(infra): change the min and max instances for prod CAE

---

.azure/applications/graphql/main.bicep
.azure/applications/service/main.bicep
.azure/applications/sync-resource-policy-information-job/main.bicep
.azure/applications/sync-subject-resource-mappings-job/main.bicep
.azure/applications/web-api-eu/main.bicep
.azure/applications/web-api-migration-job/main.bicep
.azure/applications/web-api-so/main.bicep
.azure/infrastructure/main.bicep
.azure/infrastructure/prod.bicepparam
.azure/modules/containerApp/main.bicep
.azure/modules/containerAppEnv/main.bicep
.azure/modules/containerAppJob/main.bicep

Removing the temporary code that enabled workload profiles for `test` and `yt01` only. Need to recreate the CAE in `staging` and `prod` for this. 
- #2257

fix(infra): enable workload profiles for staging and prod

---

.github/workflows/workflow-check-for-changes.yml

Minor changes like this one: https://github.com/Altinn/dialogporten-frontend/pull/2146 shouldn't trigger a full run of infra and app deployments.
Also removed slacknotifier as it's no longer in use
- #N/A

ci: avoid unecessary infra and app runs on irrelevant changes

---

docs/schema/V1/schema.verified.graphql
docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Externals/AltinnAuthorization/AuthorizedPartiesResult.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Parties/Queries/Get/PartiesDto.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/Parties/ObjectTypes.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/AuthorizedPartiesHelper.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/AuthorizedPartiesResultDto.cs
src/Digdir.Domain.Dialogporten.Infrastructure/Altinn/Authorization/LocalDevelopmentAltinnAuthorization.cs

- extend AuthorizedParty data structures with `PartyUuid`
- expose `partyUuid` in the end user parties API documentation and GraphQL schema
- include UUIDs in local development stub data
- `dotnet test --no-build --configuration Release` *(fails: The argument <path>.dll is invalid)*

feat: Add partyUuid to parties endpoint DTO

---

src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/DialogSystemLabels/Commands/BulkSet/BulkSetDialogSystemLabelCommandValidator.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/DialogSystemLabels/Commands/BulkSet/BulkSetSystemLabelCommandValidator.cs
tests/Digdir.Domain.Dialogporten.Application.Unit.Tests/Features/V1/EndUser/DialogSystemLabels/Commands/BulkSet/BulkSetSystemLabelCommandValidatorTests.cs
tests/Digdir.Domain.Dialogporten.Application.Unit.Tests/Features/V1/ServiceOwner/DialogSystemLabels/Commands/BulkSet/BulkSetSystemLabelCommandValidatorTests.cs

- enforce unique `DialogId` values in bulk set validators
- add unit tests for duplicate `DialogId`s
- `dotnet build Digdir.Domain.Dialogporten.sln -v minimal`
- `dotnet test Digdir.Domain.Dialogporten.sln --no-build --logger "trx;LogFileName=TestResults.trx"` *(fails: several integration tests fail)*

feat(validation): enforce unique bulk-set dialog ids

---

tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/DialogSystemLabels/BulkSetDialogSystemLabelTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/DialogSystemLabels/SetDialogSystemLabelTests.cs
tests/Digdir.Domain.Dialogporten.Application.Unit.Tests/Features/V1/ServiceOwner/DialogSystemLabels/Commands/BulkSetSystemLabelCommandValidatorTests.cs
tests/Digdir.Domain.Dialogporten.Application.Unit.Tests/Features/V1/ServiceOwner/DialogSystemLabels/Commands/SetSystemLabelCommandValidatorTests.cs

- add validator tests for Set and BulkSet system label commands
- add integration tests for new bulk set endpoint and single-set endpoint
- `dotnet build Digdir.Domain.Dialogporten.sln -c Release`
- `dotnet test Digdir.Domain.Dialogporten.sln -c Release` *(fails: unable to run integration tests)*

test(serviceowner): add system label command tests

---

docs/schema/V1/schema.verified.graphql
docs/schema/V1/swagger.verified.json
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/DialogDtoBase.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/EndUser/Dialogs/Queries/Search/MappingProfile.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/DialogDtoBase.cs
src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Queries/Search/MappingProfile.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/SearchDialogs/MappingProfile.cs
src/Digdir.Domain.Dialogporten.GraphQL/EndUser/SearchDialogs/ObjectTypes.cs
src/Digdir.Library.Dialogporten.WebApiClient/Features/V1/RefitterInterface.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/EndUser/Dialogs/Queries/Search/EnduserContextRevisionTests.cs
tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/Dialogs/Queries/Search/EnduserContextRevisionTests.cs

- include EnduserContextRevision in search DTOs
- map EnduserContextRevision from domain
- expose via GraphQL and update refit client
- update API schemas
- cover new field in integration tests
- `dotnet build Digdir.Domain.Dialogporten.sln -c Release`
- `dotnet test Digdir.Domain.Dialogporten.sln -c Release` *(fails: many integration tests)*

feat(search): expose enduser context revision

---

tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/EndUser/DialogSystemLabels/BulkSetDialogSystemLabelTests.cs

- add test verifying end-user bulk set works with revision ids
- `dotnet build Digdir.Domain.Dialogporten.sln -v minimal`
- `dotnet test Digdir.Domain.Dialogporten.sln -c Release --filter 'FullyQualifiedName!~Integration' --no-build`

test(end-user): add bulk set revision scenario

---

tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/EndUser/DialogSystemLabels/SetDialogSystemLabelTests.cs

- add end user SetDialogSystemLabelTests with concurrency check
- `dotnet build Digdir.Domain.Dialogporten.sln -nologo`
- `dotnet test Digdir.Domain.Dialogporten.sln -c Release --filter 'FullyQualifiedName!~Integration' -nologo`

test(enduser): add set dialog system label tests

---

tests/Digdir.Domain.Dialogporten.Application.Integration.Tests/Features/V1/ServiceOwner/DialogSystemLabels/SetDialogSystemLabelTests.cs

- extend SetDialogSystemLabelTests
- ensure concurrency mismatch returns error
- add success scenario for revision match
- `dotnet build Digdir.Domain.Dialogporten.sln -v minimal`
- `dotnet test Digdir.Domain.Dialogporten.sln --no-build --filter 'FullyQualifiedName!~Integration' -v minimal` *(fails: SwaggerSnapshotTests require Release)*

test(serviceowner): add revision match tests

---

src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogSystemLabels/BulkSet/BulkSetDialogSystemLabelsEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/EndUser/DialogSystemLabels/Set/SetDialogSystemLabelEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogSystemLabels/BulkSet/BulkSetDialogSystemLabelsEndpointSummary.cs
src/Digdir.Domain.Dialogporten.WebApi/Endpoints/V1/ServiceOwner/DialogSystemLabels/Set/SetDialogSystemLabelEndpointSummary.cs

- document service owner bulk-set system labels endpoint
- document service owner set system label endpoint
- document end user bulk-set system labels endpoint
- document end user set system label endpoint
- `dotnet build` *(fails: `dotnet: command not found`)*

docs(api): add summaries for system label endpoints

---

src/Digdir.Domain.Dialogporten.GraphQL/Common/Authentication/TokenIssuerCache.cs
src/Digdir.Domain.Dialogporten.WebApi/Common/Authentication/TokenIssuerCache.cs
tests/Digdir.Domain.Dialogporten.GraphQl.Unit.Tests/TokenIssuerCacheTests.cs
tests/Digdir.Domain.Dialogporten.WebApi.Unit.Tests/TokenIssuerCacheTests.cs

- fix semaphore release when returning early from TokenIssuerCache initialization
- add unit test ensuring concurrent calls don't deadlock
- `dotnet build tests/Digdir.Domain.Dialogporten.WebApi.Unit.Tests/Digdir.Domain.Dialogporten.WebApi.Unit.Tests.csproj -c Release --verbosity minimal`
- `dotnet test tests/Digdir.Domain.Dialogporten.WebApi.Unit.Tests/Digdir.Domain.Dialogporten.WebApi.Unit.Tests.csproj -c Release --no-build --verbosity minimal`

fix: Fix TokenIssuerCache initialization semaphore

---

tests/k6/tests/enduser/all-tests.js
tests/k6/tests/enduser/dialogBulkSystemLabels.js
tests/k6/tests/serviceowner/all-tests.js
tests/k6/tests/serviceowner/dialogBulkSystemLabels.js

- add k6 tests for service owner bulk system label API
- add k6 tests for end user bulk system label API including unauthorized case
- `dotnet build Digdir.Domain.Dialogporten.sln -c Release`
- `dotnet test Digdir.Domain.Dialogporten.sln --no-build --configuration Release --filter 'FullyQualifiedName!~Integration'`

test(k6): add bulk API e2e tests

---

scripts/database-forwarder/forward.sh

When there was any upgrade prompts for `az cli`, the script would hang on "Connecting to host ..."
Adding env variables to ensure it doesn't give any interactive prompts. 
- #N/A

trivial(forwarder): ensure script doesn't hang when new cli version is available

---

.github/workflows/workflow-publish-nuget.yml
src/Digdir.Library.Dialogporten.WebApiClient/README.md

#2423 changed from project ref. to Target BeforeBuild for WebAPI, this requires a `dotnet restore` before we do `dotnet pack`

fix(ci): Restore dependencies before 'dotnet pack'

---

.azure/infrastructure/main.bicep
.azure/infrastructure/prod.bicepparam
.azure/infrastructure/staging.bicepparam
.azure/infrastructure/test.bicepparam
.azure/infrastructure/yt01.bicepparam
.azure/modules/postgreSql/create.bicep

Seems like principalName is empty if the "user" is a service principal, so supplying it directly from params
- #2171

fix(infra): supply principal name as param for postgresql

---

src/Digdir.Domain.Dialogporten.Domain/Parties/SystemUserIdentifier.cs

The list auth for system users fails because we're using the wrong prefix in the call to authorized parties.

fix: Use correct systemuser prefix

---

src/Digdir.Domain.Dialogporten.WebApi/Common/Authentication/UserTypeValidationMiddleware.cs
tests/k6/common/token.js

This adds a per-endpoint-policy validation to the user type validation middleware, ensuring that each endpoint cannot be accessed unless the correct user type for that endpoint is authenticated.
Changes include an update to the e2e tests, which conflated the claims (in particular scopes) for service owner and end user tokens. Now this is properly separated to closer mimic the actual maskinporten/id-porten tokens. 
- #2538

fix: Add user type per endpoint policy validation

---

src/Digdir.Domain.Dialogporten.Infrastructure/InfrastructureExtensions.cs

RR data is not very volatile, upping the use of stale data to improve resillience of RR downtime.

fix(auth): Increase FailSafeMaxDuration for RR data

---

.github/workflows/ci-cd-prod.yml
.github/workflows/workflow-publish-nuget.yml

When running ci-cd-production.yaml it used `main` as a ref. This would result in that the package had `main` as a base instead of the actual tag to be deployed. 
- #N/A

fix(ci): ensure we checkout the proper ref when publishing nuget package

---

src/Digdir.Domain.Dialogporten.Infrastructure/Persistence/FusionCache/FeatureMetricServiceResourceCache.cs

This pr attempts to not cache null in FeatureMetricServiceResourceCache by opting-out from fusionCache.GetOrAdd, and introducing our own stampeding herd protection.

fix(app): Attempt to not cache null in FeatureMetricServiceResourceCache
